package uk.gov.pmrv.api.authorization.regulator.domain;

public enum RegulatorPermissionGroup {

    MANAGE_USERS_AND_CONTACTS,
    ADD_OPERATOR_ADMIN,
    ASSIGN_REASSIGN_TASKS,
    MANAGE_VERIFICATION_BODIES,

    REVIEW_INSTALLATION_ACCOUNT,
    
    REVIEW_PERMIT_APPLICATION,
    PEER_REVIEW_PERMIT_APPLICATION,
    
    REVIEW_PERMIT_SURRENDER,
    PEER_REVIEW_PERMIT_SURRENDER,
    
    SUBMIT_PERMIT_REVOCATION,
    PEER_REVIEW_PERMIT_REVOCATION,
    
    REVIEW_PERMIT_NOTIFICATION,
    PEER_REVIEW_PERMIT_NOTIFICATION,
    
    SUBMIT_REVIEW_PERMIT_VARIATION,
    PEER_REVIEW_PERMIT_VARIATION,

    REVIEW_AER
    
}
