/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AccountUserContact {
  accountId?: number;
  accountName?: string;
  accountStatus?:
    | 'AWAITING_RATIONALISATION'
    | 'AWAITING_REVOCATION'
    | 'AWAITING_SURRENDER'
    | 'AWAITING_TRANSFER'
    | 'CEASED_OPERATIONS'
    | 'COMMISSION_LIST'
    | 'DEEMED_WITHDRAWN'
    | 'DENIED'
    | 'EXEMPT'
    | 'EXEMPT_COMMERCIAL'
    | 'EXEMPT_NON_COMMERCIAL'
    | 'LIVE'
    | 'NEW'
    | 'PERMIT_REFUSED'
    | 'PRIOR_COMPLIANCE_LIST'
    | 'RATIONALISED'
    | 'REMOVED_FROM_COMMISSION_LIST'
    | 'REVOKED'
    | 'SURRENDERED'
    | 'TRANSFERRED'
    | 'UNAPPROVED';
  accountType?: 'AVIATION' | 'INSTALLATION';
  authorityStatus?: 'ACCEPTED' | 'ACTIVE' | 'DISABLED' | 'PENDING' | 'TEMP_DISABLED' | 'TEMP_DISABLED_PENDING';
  email?: string;
  isFinancialContact?: boolean;
  isPrimaryContact?: boolean;
  isSecondaryContact?: boolean;
  isServiceContact?: boolean;
  lastLogon?: string;
  legalEntityName?: string;
  name?: string;
  permitId?: string;
  permitType?: string;
  role?: string;
  telephone?: string;
}
