/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';
import { LocationDTO } from './locationDTO';

export interface AccountDetailsDTO {
  accountType?: 'AVIATION' | 'INSTALLATION';
  applicationType?: 'NEW_PERMIT' | 'TRANSFER';
  companyReferenceNumber?: string;
  emitterType?: 'GHGE' | 'HSE';
  id?: number;
  installationCategory?: 'A' | 'A_LOW_EMITTER' | 'B' | 'C' | 'N_A';
  legalEntityAddress?: AddressDTO;
  legalEntityName?: string;
  legalEntityType?: 'LIMITED_COMPANY' | 'OTHER' | 'PARTNERSHIP' | 'SOLE_TRADER';
  location?: LocationDTO;
  name?: string;
  permitId?: string;
  registryId?: number;
  siteName?: string;
  sopId?: number;
  status?:
    | 'AWAITING_RATIONALISATION'
    | 'AWAITING_REVOCATION'
    | 'AWAITING_SURRENDER'
    | 'AWAITING_TRANSFER'
    | 'CEASED_OPERATIONS'
    | 'COMMISSION_LIST'
    | 'DEEMED_WITHDRAWN'
    | 'DENIED'
    | 'EXEMPT'
    | 'EXEMPT_COMMERCIAL'
    | 'EXEMPT_NON_COMMERCIAL'
    | 'LIVE'
    | 'NEW'
    | 'PERMIT_REFUSED'
    | 'PRIOR_COMPLIANCE_LIST'
    | 'RATIONALISED'
    | 'REMOVED_FROM_COMMISSION_LIST'
    | 'REVOKED'
    | 'SURRENDERED'
    | 'TRANSFERRED'
    | 'UNAPPROVED';
  subsistenceCategory?: 'A' | 'B' | 'C' | 'H' | 'O' | 'S' | 'Z';
}
