/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Abbreviations } from './abbreviations';
import { AdditionalDocuments } from './additionalDocuments';
import { AerRegulatedActivity } from './aerRegulatedActivity';
import { ConfidentialityStatement } from './confidentialityStatement';
import { EmissionPoint } from './emissionPoint';
import { EmissionSource } from './emissionSource';
import { NaceCodes } from './naceCodes';
import { PollutantRegisterActivities } from './pollutantRegisterActivities';
import { SourceStream } from './sourceStream';

export interface Aer {
  abbreviations: Abbreviations;
  additionalDocuments: AdditionalDocuments;
  confidentialityStatement: ConfidentialityStatement;
  emissionPoints?: Array<EmissionPoint>;
  emissionSources?: Array<EmissionSource>;
  monitoringApproachTypes?: Array<
    'CALCULATION' | 'FALLBACK' | 'INHERENT_CO2' | 'MEASUREMENT' | 'N2O' | 'PFC' | 'TRANSFERRED_CO2'
  >;
  naceCodes: NaceCodes;
  pollutantRegisterActivities: PollutantRegisterActivities;
  regulatedActivities?: Array<AerRegulatedActivity>;
  sourceStreams?: Array<SourceStream>;
}
