/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CalculationSourceStreamCategoryAppliedTier } from './calculationSourceStreamCategoryAppliedTier';
import { SamplingPlan } from './samplingPlan';

export interface CalculationMonitoringApproach {
  approachDescription: string;
  samplingPlan: SamplingPlan;
  sourceStreamCategoryAppliedTiers?: Array<CalculationSourceStreamCategoryAppliedTier>;
  type?: 'CALCULATION' | 'FALLBACK' | 'INHERENT_CO2' | 'MEASUREMENT' | 'N2O' | 'PFC' | 'TRANSFERRED_CO2';
}
