/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NoHighestRequiredTierJustification } from './noHighestRequiredTierJustification';

export interface CalculationActivityData {
  isHighestRequiredTier?: boolean;
  measurementDevicesOrMethods?: Array<string>;
  noHighestRequiredTierJustification?: NoHighestRequiredTierJustification;
  tier: 'NO_TIER' | 'TIER_1' | 'TIER_2' | 'TIER_3' | 'TIER_4';
  uncertainty:
    | 'LESS_OR_EQUAL_10_0'
    | 'LESS_OR_EQUAL_12_5'
    | 'LESS_OR_EQUAL_15_0'
    | 'LESS_OR_EQUAL_17_5'
    | 'LESS_OR_EQUAL_1_5'
    | 'LESS_OR_EQUAL_2_5'
    | 'LESS_OR_EQUAL_5_0'
    | 'LESS_OR_EQUAL_7_5'
    | 'N_A';
}
