/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CalculationNetCalorificValueStandardReferenceSource {
  defaultValue?: string;
  otherTypeDetails?: string;
  type:
    | 'CONSERVATIVE_ESTIMATION'
    | 'IN_HOUSE_CALCULATION'
    | 'JEP_GUIDANCE_FOR_MONITORING_AND_REPORTING'
    | 'LABORATORY_ANALYSIS'
    | 'LITERATURE_VALUE_AGREED'
    | 'MONITORING_AND_REPORTING_REGULATION'
    | 'OTHER'
    | 'PAST_ANALYSIS'
    | 'SITE_SPECIFIC_ANALYSIS'
    | 'STOICHIOMETRIC_CALCULATION'
    | 'SUPPLIER_ANALYSIS_DATA'
    | 'UK_NATIONAL_GREENHOUSE_GAS_INVENTORY';
}
