/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CalculationCarbonContentStandardReferenceSource {
  defaultValue?: string;
  otherTypeDetails?: string;
  type:
    | 'IN_HOUSE_CALCULATION'
    | 'LABORATORY_ANALYSIS'
    | 'MONITORING_REPORTING_REGULATION_ANNEX_VI_SECTION2_TABLE_4'
    | 'MONITORING_REPORTING_REGULATION_ARTICLE_25_1'
    | 'OTHER'
    | 'PAST_ANALYSIS'
    | 'SUPPLIER_ANALYSIS_DATA'
    | 'UK_STEEL_CARBON_IN_SCRAP_AND_ALLOYS_PROTOCOL_LATEST_VERSION';
}
