/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CalculationOxidationFactorStandardReferenceSource {
  defaultValue?: string;
  otherTypeDetails?: string;
  type:
    | 'LABORATORY_ANALYSIS'
    | 'MONITORING_REPORTING_REGULATION_ANNEX_II_SECTION_2_3'
    | 'OTHER'
    | 'UK_NATIONAL_GREENHOUSE_GAS_INVENTORY';
}
