/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CalculationSourceStreamCategory {
  annualEmittedCO2Tonnes: number;
  calculationMethod: 'MASS_BALANCE' | 'STANDARD';
  categoryType: 'DE_MINIMIS' | 'MAJOR' | 'MARGINAL' | 'MINOR';
  emissionSources?: Array<string>;
  sourceStream: string;
}
