/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CalculationActivityData } from './calculationActivityData';
import { CalculationBiomassFraction } from './calculationBiomassFraction';
import { CalculationCarbonContent } from './calculationCarbonContent';
import { CalculationConversionFactor } from './calculationConversionFactor';
import { CalculationEmissionFactor } from './calculationEmissionFactor';
import { CalculationNetCalorificValue } from './calculationNetCalorificValue';
import { CalculationOxidationFactor } from './calculationOxidationFactor';
import { CalculationSourceStreamCategory } from './calculationSourceStreamCategory';

export interface CalculationSourceStreamCategoryAppliedTier {
  activityData: CalculationActivityData;
  biomassFraction: CalculationBiomassFraction;
  carbonContent: CalculationCarbonContent;
  conversionFactor: CalculationConversionFactor;
  emissionFactor: CalculationEmissionFactor;
  netCalorificValue: CalculationNetCalorificValue;
  oxidationFactor: CalculationOxidationFactor;
  sourceStreamCategory: CalculationSourceStreamCategory;
}
