/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReducedSamplingFrequencyJustification } from './reducedSamplingFrequencyJustification';

export interface CalculationAnalysisMethod {
  analysis: string;
  files?: Array<string>;
  frequencyMeetsMinRequirements?: boolean;
  laboratoryAccredited: boolean;
  laboratoryName: string;
  reducedSamplingFrequencyJustification?: ReducedSamplingFrequencyJustification;
  samplingFrequency: 'ANNUALLY' | 'BI_ANNUALLY' | 'CONTINUOUS' | 'DAILY' | 'MONTHLY' | 'OTHER' | 'QUARTERLY' | 'WEEKLY';
  samplingFrequencyOtherDetails?: string;
  subParameter?: string;
}
