/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FallbackSourceStreamCategory {
  annualEmittedCO2Tonnes: number;
  categoryType: 'DE_MINIMIS' | 'MAJOR' | 'MARGINAL' | 'MINOR';
  emissionSources?: Array<string>;
  measurementDevicesOrMethods?: Array<string>;
  sourceStream: string;
  uncertainty?:
    | 'LESS_OR_EQUAL_10_0'
    | 'LESS_OR_EQUAL_12_5'
    | 'LESS_OR_EQUAL_15_0'
    | 'LESS_OR_EQUAL_17_5'
    | 'LESS_OR_EQUAL_1_5'
    | 'LESS_OR_EQUAL_2_5'
    | 'LESS_OR_EQUAL_5_0'
    | 'LESS_OR_EQUAL_7_5'
    | 'N_A';
}
