/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LegalEntityDTO } from './legalEntityDTO';
import { LocationDTO } from './locationDTO';

export interface InstallationAccountOpeningSubmitApplicationCreateActionPayload {
  accountType: 'AVIATION' | 'INSTALLATION';
  commencementDate: string;
  competentAuthority: 'ENGLAND' | 'NORTHERN_IRELAND' | 'OPRED' | 'SCOTLAND' | 'WALES';
  emissionTradingScheme: 'CORSIA' | 'EU_ETS_INSTALLATIONS' | 'UK_ETS_AVIATION' | 'UK_ETS_INSTALLATIONS';
  legalEntity: LegalEntityDTO;
  location: LocationDTO;
  name: string;
  payloadType?: 'EMPTY_PAYLOAD' | 'INSTALLATION_ACCOUNT_OPENING_SUBMIT_APPLICATION_PAYLOAD';
  siteName: string;
}
