/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MeasurementDevice {
  location: string;
  otherTypeName?: string;
  reference: string;
  type:
    | 'BALANCE'
    | 'BELLOWS_METER'
    | 'BELT_WEIGHER'
    | 'CORIOLIS_METER'
    | 'ELECTRONIC_VOLUME_CONVERSION_INSTRUMENT'
    | 'GAS_CHROMATOGRAPH'
    | 'LEVEL_GAUGE'
    | 'ORIFICE_METER'
    | 'OTHER'
    | 'OVALRAD_METER'
    | 'ROTARY_METER'
    | 'TANK_DIP'
    | 'TURBINE_METER'
    | 'ULTRASONIC_METER'
    | 'VENTURI_METER'
    | 'VORTEX_METER'
    | 'WEIGHBRIDGE'
    | 'WEIGHSCALE';
}
