/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { N2OSourceStreamCategoryAppliedTier } from './n2OSourceStreamCategoryAppliedTier';
import { ProcedureForm } from './procedureForm';
import { ProcedureOptionalForm } from './procedureOptionalForm';

export interface N2OMonitoringApproach {
  approachDescription: string;
  emissionDetermination: ProcedureForm;
  gasFlowCalculation: ProcedureOptionalForm;
  nitrousOxideConcentrationDetermination: ProcedureForm;
  nitrousOxideEmissionsDetermination: ProcedureForm;
  operationalManagement: ProcedureForm;
  quantityMaterials: ProcedureForm;
  quantityProductDetermination: ProcedureForm;
  referenceDetermination: ProcedureForm;
  sourceStreamCategoryAppliedTiers?: Array<N2OSourceStreamCategoryAppliedTier>;
  type?: 'CALCULATION' | 'FALLBACK' | 'INHERENT_CO2' | 'MEASUREMENT' | 'N2O' | 'PFC' | 'TRANSFERRED_CO2';
}
