/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface OperatorInvitedUserInfoDTO {
  accountInstallationName?: string;
  email?: string;
  firstName?: string;
  invitationStatus?:
    | 'ACCEPTED'
    | 'PENDING_USER_ENABLE'
    | 'PENDING_USER_REGISTRATION'
    | 'PENDING_USER_REGISTRATION_NO_PASSWORD';
  lastName?: string;
  roleCode?: string;
}
