/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PermitCessation {
  allowancesSurrenderDate?: string;
  annualReportableEmissions: number;
  determinationOutcome: 'APPROVED' | 'REJECTED';
  notes: string;
  noticeType: 'NO_PROSPECT_OF_FURTHER_ALLOWANCES' | 'SATISFIED_WITH_REQUIREMENTS_COMPLIANCE';
  numberOfSurrenderAllowances?: number;
  subsistenceFeeRefunded: boolean;
}
