/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PermitVariationModification {
  otherSummary?: string;
  type:
    | 'CALCULATION_TO_MEASUREMENT_METHODOLOGIES'
    | 'COMPANY_NAME_NOT_DUE_TO_OWNERSHIP_CHANGE'
    | 'COMPETENT_AUTHORITY'
    | 'DEFAULT_VALUE_OR_ESTIMATION_METHOD'
    | 'EMISSION_SOURCES'
    | 'GRID_REFERENCE'
    | 'INSTALLATION_ADDRESS'
    | 'INSTALLATION_CATEGORY'
    | 'INSTALLATION_NAME'
    | 'INSTALLATION_SUB'
    | 'METER_LOCATION_DESCRIPTION'
    | 'METER_RENAMING'
    | 'METHODS'
    | 'MONITORING_REPORT_METHODOLOGY_4_4_OR_4_6'
    | 'NEW_SOURCE_STREAMS'
    | 'NOTWITHSTANDING_ARTICLE_47_8'
    | 'OTHER_MONITORING_METHODOLOGY_PLAN'
    | 'OTHER_MONITORING_PLAN'
    | 'OTHER_NON_SIGNFICANT'
    | 'QUANTIFICATION_METHODOLOGY_FOR_EMISSIONS'
    | 'REGISTERED_OFFICE_ADDRESS'
    | 'RELEASE_EMISSION_POINT_DESCRIPTION'
    | 'SOURCE_STREAMS_CATEGORISATION'
    | 'TIER_APPLIED';
}
