/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FollowUp } from './followUp';

export interface PermitNotificationReviewDecision {
  followUp?: FollowUp;
  notes?: string;
  officialNotice: string;
  type: 'ACCEPTED' | 'REJECTED';
}
