/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Abbreviations } from './abbreviations';
import { AdditionalDocuments } from './additionalDocuments';
import { ConfidentialityStatement } from './confidentialityStatement';
import { DataFlowActivities } from './dataFlowActivities';
import { EmissionPoint } from './emissionPoint';
import { EmissionSource } from './emissionSource';
import { EmissionSummary } from './emissionSummary';
import { EnvironmentalManagementSystem } from './environmentalManagementSystem';
import { EnvironmentalPermitsAndLicences } from './environmentalPermitsAndLicences';
import { EstimatedAnnualEmissions } from './estimatedAnnualEmissions';
import { InstallationDescription } from './installationDescription';
import { ManagementProceduresDefinition } from './managementProceduresDefinition';
import { MeasurementDeviceOrMethod } from './measurementDeviceOrMethod';
import { MonitoringMethodologyPlans } from './monitoringMethodologyPlans';
import { MonitoringReporting } from './monitoringReporting';
import { PermitMonitoringApproachSection } from './permitMonitoringApproachSection';
import { RegulatedActivity } from './regulatedActivity';
import { SourceStream } from './sourceStream';
import { UncertaintyAnalysis } from './uncertaintyAnalysis';

export interface Permit {
  abbreviations: Abbreviations;
  additionalDocuments: AdditionalDocuments;
  assessAndControlRisk?: ManagementProceduresDefinition;
  assignmentOfResponsibilities?: ManagementProceduresDefinition;
  confidentialityStatement: ConfidentialityStatement;
  controlOfOutsourcedActivities?: ManagementProceduresDefinition;
  correctionsAndCorrectiveActions?: ManagementProceduresDefinition;
  dataFlowActivities?: DataFlowActivities;
  emissionPoints?: Array<EmissionPoint>;
  emissionSources?: Array<EmissionSource>;
  emissionSummaries?: Array<EmissionSummary>;
  environmentalManagementSystem?: EnvironmentalManagementSystem;
  environmentalPermitsAndLicences: EnvironmentalPermitsAndLicences;
  estimatedAnnualEmissions: EstimatedAnnualEmissions;
  installationDescription: InstallationDescription;
  managementProceduresExist: boolean;
  measurementDevicesOrMethods?: Array<MeasurementDeviceOrMethod>;
  monitoringApproaches?: { [key: string]: PermitMonitoringApproachSection };
  monitoringMethodologyPlans: MonitoringMethodologyPlans;
  monitoringPlanAppropriateness?: ManagementProceduresDefinition;
  monitoringReporting?: MonitoringReporting;
  qaDataFlowActivities?: ManagementProceduresDefinition;
  qaMeteringAndMeasuringEquipment?: ManagementProceduresDefinition;
  recordKeepingAndDocumentation?: ManagementProceduresDefinition;
  regulatedActivities?: Array<RegulatedActivity>;
  reviewAndValidationOfData?: ManagementProceduresDefinition;
  siteDiagrams?: Array<string>;
  sourceStreams?: Array<SourceStream>;
  uncertaintyAnalysis: UncertaintyAnalysis;
}
