/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstallationOperatorDetails } from './installationOperatorDetails';
import { Permit } from './permit';

export interface PermitContainer {
  activationDate?: string;
  annualEmissionsTargets?: { [key: string]: number };
  installationOperatorDetails: InstallationOperatorDetails;
  permit: Permit;
  permitAttachments?: { [key: string]: string };
  permitType: 'GHGE' | 'HSE';
}
