/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermitReviewDecisionRequiredChange } from './permitReviewDecisionRequiredChange';

export interface PermitVariationReviewDecision {
  notes?: string;
  requiredChanges?: Array<PermitReviewDecisionRequiredChange>;
  type: 'ACCEPTED' | 'OPERATOR_AMENDS_NEEDED' | 'REJECTED';
  variationScheduleItems?: Array<string>;
}
