/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PermitRevocation {
  activitiesStopped: boolean;
  annualEmissionsReportDate?: string;
  annualEmissionsReportRequired: boolean;
  effectiveDate: string;
  feeCharged: boolean;
  feeDate?: string;
  feeDetails?: string;
  reason: string;
  stoppedDate?: string;
  surrenderDate?: string;
  surrenderRequired: boolean;
}
