/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileInfoDTO } from './fileInfoDTO';

export interface RegulatorUserDTORes {
  email: string;
  firstName: string;
  jobTitle: string;
  lastName: string;
  mobileNumber?: string;
  phoneNumber: string;
  signature?: FileInfoDTO;
  status?: 'DELETED' | 'PENDING' | 'REGISTERED';
  termsVersion?: number;
}
