/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestMetadata } from './requestMetadata';

export interface RequestDetailsDTO {
  creationDate?: string;
  id?: string;
  requestMetadata?: RequestMetadata;
  requestStatus?: 'APPROVED' | 'CANCELLED' | 'COMPLETED' | 'IN_PROGRESS' | 'REJECTED' | 'WITHDRAWN';
  requestType?:
    | 'AER'
    | 'INSTALLATION_ACCOUNT_OPENING'
    | 'PERMIT_ISSUANCE'
    | 'PERMIT_NOTIFICATION'
    | 'PERMIT_NOTIFICATION_FOLLOW_UP'
    | 'PERMIT_REVOCATION'
    | 'PERMIT_SURRENDER'
    | 'PERMIT_TRANSFER'
    | 'PERMIT_VARIATION'
    | 'SYSTEM_MESSAGE_NOTIFICATION';
}
