/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountingEmissions } from './accountingEmissions';
import { ProcedureForm } from './procedureForm';
import { ProcedureOptionalForm } from './procedureOptionalForm';
import { ReceivingTransferringInstallation } from './receivingTransferringInstallation';
import { TemperaturePressure } from './temperaturePressure';

export interface TransferredCO2MonitoringApproach {
  accountingEmissions: AccountingEmissions;
  approachDescription: string;
  deductionsToAmountOfTransferredCO2: ProcedureOptionalForm;
  procedureForLeakageEvents: ProcedureOptionalForm;
  quantificationMethodologies: ProcedureForm;
  receivingTransferringInstallations?: Array<ReceivingTransferringInstallation>;
  temperaturePressure: TemperaturePressure;
  transferOfCO2: ProcedureForm;
  type?: 'CALCULATION' | 'FALLBACK' | 'INHERENT_CO2' | 'MEASUREMENT' | 'N2O' | 'PFC' | 'TRANSFERRED_CO2';
}
