/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserFeedbackDto {
  creatingAccountRate:
    | 'DISSATISFIED'
    | 'NEITHER_SATISFIED_NOR_DISSATISFIED'
    | 'NOT_APPLICABLE_NOT_USED_YET'
    | 'SATISFIED'
    | 'VERY_DISSATISFIED'
    | 'VERY_SATISFIED';
  creatingAccountRateReason?: string;
  improvementSuggestion?: string;
  onBoardingRate:
    | 'DISSATISFIED'
    | 'NEITHER_SATISFIED_NOR_DISSATISFIED'
    | 'NOT_APPLICABLE_NOT_USED_YET'
    | 'SATISFIED'
    | 'VERY_DISSATISFIED'
    | 'VERY_SATISFIED';
  onBoardingRateReason?: string;
  onlineGuidanceRate:
    | 'DISSATISFIED'
    | 'NEITHER_SATISFIED_NOR_DISSATISFIED'
    | 'NOT_APPLICABLE_NOT_USED_YET'
    | 'SATISFIED'
    | 'VERY_DISSATISFIED'
    | 'VERY_SATISFIED';
  onlineGuidanceRateReason?: string;
  satisfactionRate:
    | 'DISSATISFIED'
    | 'NEITHER_SATISFIED_NOR_DISSATISFIED'
    | 'NOT_APPLICABLE_NOT_USED_YET'
    | 'SATISFIED'
    | 'VERY_DISSATISFIED'
    | 'VERY_SATISFIED';
  satisfactionRateReason?: string;
  tasksRate:
    | 'DISSATISFIED'
    | 'NEITHER_SATISFIED_NOR_DISSATISFIED'
    | 'NOT_APPLICABLE_NOT_USED_YET'
    | 'SATISFIED'
    | 'VERY_DISSATISFIED'
    | 'VERY_SATISFIED';
  tasksRateReason?: string;
  userRegistrationRate:
    | 'DISSATISFIED'
    | 'NEITHER_SATISFIED_NOR_DISSATISFIED'
    | 'NOT_APPLICABLE_NOT_USED_YET'
    | 'SATISFIED'
    | 'VERY_DISSATISFIED'
    | 'VERY_SATISFIED';
  userRegistrationRateReason?: string;
}
