/**
 * PMRV API Documentation
 * Back-end REST API documentation for the UK PMRV application
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.58.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';
import { AdminVerifierUserInvitationDTO } from './adminVerifierUserInvitationDTO';

export interface VerificationBodyCreationDTO {
  accreditationReferenceNumber: string;
  address: AddressDTO;
  adminVerifierUserInvitation: AdminVerifierUserInvitationDTO;
  emissionTradingSchemes?: Array<'CORSIA' | 'EU_ETS_INSTALLATIONS' | 'UK_ETS_AVIATION' | 'UK_ETS_INSTALLATIONS'>;
  name: string;
}
