FROM nginx:1.22
ENV XAUTH $HOME/.Xauthority

# preparing the software stack
RUN apt-get update
RUN apt-get install -y apache2-utils nano curl
RUN rm /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/nginx.conf

# copying the minimum configuration
COPY confs_aws/nginx.conf /etc/nginx/nginx.conf
COPY confs_aws/proxy_headers.conf /etc/nginx/proxy_headers.conf
COPY confs_aws/global_security_headers.conf /etc/nginx/global_security_headers.conf
COPY confs_aws/kill_cache.conf /etc/nginx/kill_cache.conf
COPY confs_aws/entrypoint.sh /usr/local/bin/entrypoint.sh
COPY confs_aws/ukpmrv.net.conf /etc/nginx/conf.d/ukpmrv.net.conf

ENTRYPOINT ["/bin/bash","/usr/local/bin/entrypoint.sh"]
