package uk.gov.pmrv.api.migration.permit.managementprocedures;

public enum ManagementProceduresDefinitionType {
    ASSESS_AND_CONTROL_RISKS,
    ASSIGNMENT_OF_RESPONSIBILITIES,
    CONTROL_OF_OUTSOURCED_ACTIVITIES,
    CORRECTIONS_AND_CORRECTIVE_ACTIONS,
    MONITORING_PLAN_APPROPRIATENESS,
    QA_DATA_FLOW_ACTIVITIES,
    QA_METERING_AND_MEASURING_EQUIPMENT,
    RECORD_KEEPING_AND_DOCUMENTATION,
    REVIEW_AND_VALIDATION_OF_DATA
}
