package uk.gov.pmrv.api.permit.domain.monitoringapproaches.calculation;

public enum CalculationEmissionFactorStandardReferenceSourceType {

    UK_NATIONAL_GREENHOUSE_GAS_INVENTORY,
    MONITORING_REPORTING_REGULATION_ARTICLE_36_3,
    MONITORING_REPORTING_REGULATION_ARTICLE_38_2,
    MONITORING_REPORTING_REGULATION_ANNEX_IV_SECTION_1_C1,
    MONITORING_REPORTING_REGULATION_ANNEX_IV_SECTION_1_C2,
    MONITORING_REPORTING_REGULATION_ANNEX_IV_SECTION_1_D,
    MONITORING_REPORTING_REGULATION_ANNEX_IV_SECTION_2_B,
    MONITORING_REPORTING_REGULATION_ANNEX_IV_SECTION_9_B,
    MONITORING_REPORTING_REGULATION_ANNEX_IV_SECTION_12_B,
    MONITORING_REPORTING_REGULATION_ANNEX_VI_SECTION_1_TABLE_1,
    MONITORING_REPORTING_REGULATION_ANNEX_VI_SECTION_2_TABLE_2,
    MONITORING_REPORTING_REGULATION_ANNEX_VI_SECTION_2_TABLE_3,
    MONITORING_REPORTING_REGULATION_ANNEX_VI_SECTION_2_TABLE_4,
    MONITORING_REPORTING_REGULATION_ANNEX_VI_SECTION_2_TABLE_5,
    JEP_GUIDANCE,
    BRITISH_CERAMIC_CONFEDERATION,
    LABORATORY_ANALYSIS,
    PAST_ANALYSIS,
    SUPPLIER_ANALYSIS,
    LITERATURE_VALUE_AGREED_WITH_UK_ETS_REGULATOR,
    IN_HOUSE_CALCULATION,
    STOICHIOMETRIC_CALCULATION,
    CONSERVATIVE_ESTIMATION,
    
    OTHER
    
}
