package uk.gov.pmrv.api.permit.domain.monitoringapproaches.calculation;

public enum CalculationNetCalorificValueStandardReferenceSourceType {

    UK_NATIONAL_GREENHOUSE_GAS_INVENTORY,
    MONITORING_AND_REPORTING_REGULATION,
    JEP_GUIDANCE_FOR_MONITORING_AND_REPORTING,
    LABORATORY_ANALYSIS,
    SITE_SPECIFIC_ANALYSIS,
    PAST_ANALYSIS,
    SUPPLIER_ANALYSIS_DATA,
    LITERATURE_VALUE_AGREED,
    IN_HOUSE_CALCULATION,
    STOICHIOMETRIC_CALCULATION,
    CONSERVATIVE_ESTIMATION,
    OTHER
}
