package uk.gov.pmrv.api.permit.domain.monitoringapproaches.calculation;

public enum CalculationCarbonContentStandardReferenceSourceType {

    MONITORING_REPORTING_REGULATION_ARTICLE_25_1,
    MONITORING_REPORTING_REGULATION_ANNEX_VI_SECTION2_TABLE_4,
    UK_STEEL_CARBON_IN_SCRAP_AND_ALLOYS_PROTOCOL_LATEST_VERSION,
    LABORATORY_ANALYSIS,
    SUPPLIER_ANALYSIS_DATA,
    PAST_ANALYSIS,
    IN_HOUSE_CALCULATION,
    OTHER
}
