package uk.gov.pmrv.api.workflow.request.core.domain.enumeration;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public enum RequestTaskActionType {

    // Installation Account relevant request task actions
    INSTALLATION_ACCOUNT_OPENING_AMEND_APPLICATION,
    INSTALLATION_ACCOUNT_OPENING_SUBMIT_DECISION,
    INSTALLATION_ACCOUNT_OPENING_ARCHIVE,

    // Message relevant request task action
    SYSTEM_MESSAGE_DISMISS,

    // Permit Issuance relevant task action types
    PERMIT_ISSUANCE_SAVE_APPLICATION,
    PERMIT_ISSUANCE_UPLOAD_SECTION_ATTACHMENT,
    PERMIT_ISSUANCE_SUBMIT_APPLICATION,
    PERMIT_ISSUANCE_SAVE_APPLICATION_REVIEW,
    PERMIT_ISSUANCE_SAVE_REVIEW_GROUP_DECISION,
    PERMIT_ISSUANCE_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT,
    PERMIT_ISSUANCE_SAVE_REVIEW_DETERMINATION,
    PERMIT_ISSUANCE_NOTIFY_OPERATOR_FOR_DECISION,
    PERMIT_ISSUANCE_REQUEST_PEER_REVIEW,
    PERMIT_ISSUANCE_REVIEW_RETURN_FOR_AMENDS,
    PERMIT_ISSUANCE_REVIEW_SUBMIT_PEER_REVIEW_DECISION,
    PERMIT_ISSUANCE_SAVE_APPLICATION_AMEND,
    PERMIT_ISSUANCE_RECALL_FROM_AMENDS,
    PERMIT_ISSUANCE_SUBMIT_APPLICATION_AMEND,
    
    // Permit surrender task actions
    PERMIT_SURRENDER_SAVE_APPLICATION,
    PERMIT_SURRENDER_UPLOAD_ATTACHMENT,
    PERMIT_SURRENDER_SUBMIT_APPLICATION,
    PERMIT_SURRENDER_SAVE_REVIEW_GROUP_DECISION,
    PERMIT_SURRENDER_SAVE_REVIEW_DETERMINATION,
    PERMIT_SURRENDER_NOTIFY_OPERATOR_FOR_DECISION,
    PERMIT_SURRENDER_CANCEL_APPLICATION,
    PERMIT_SURRENDER_REQUEST_PEER_REVIEW,
    PERMIT_SURRENDER_REVIEW_SUBMIT_PEER_REVIEW_DECISION,
    PERMIT_SURRENDER_SAVE_CESSATION,
    PERMIT_SURRENDER_CESSATION_NOTIFY_OPERATOR_FOR_DECISION,
    
    // Permit revocation task actions
    PERMIT_REVOCATION_SAVE_APPLICATION,
    PERMIT_REVOCATION_NOTIFY_OPERATOR_FOR_SUBMISSION,
    PERMIT_REVOCATION_CANCEL_APPLICATION,
    PERMIT_REVOCATION_REQUEST_PEER_REVIEW,
    PERMIT_REVOCATION_SUBMIT_PEER_REVIEW_DECISION,
    PERMIT_REVOCATION_WITHDRAW_APPLICATION,
    PERMIT_REVOCATION_UPLOAD_ATTACHMENT,
    PERMIT_REVOCATION_NOTIFY_OPERATOR_FOR_WITHDRAWAL,
    PERMIT_REVOCATION_SAVE_CESSATION,
    PERMIT_REVOCATION_NOTIFY_OPERATOR_FOR_CESSATION,

    // Permit notification task actions
    PERMIT_NOTIFICATION_SAVE_APPLICATION,
    PERMIT_NOTIFICATION_UPLOAD_ATTACHMENT,
    PERMIT_NOTIFICATION_SUBMIT_APPLICATION,
    PERMIT_NOTIFICATION_SAVE_REVIEW_GROUP_DECISION,
    PERMIT_NOTIFICATION_NOTIFY_OPERATOR_FOR_DECISION,
    PERMIT_NOTIFICATION_CANCEL_APPLICATION,
    PERMIT_NOTIFICATION_REQUEST_PEER_REVIEW,
    PERMIT_NOTIFICATION_REVIEW_SUBMIT_PEER_REVIEW_DECISION,
    PERMIT_NOTIFICATION_FOLLOW_UP_EXTEND_DATE,
    PERMIT_NOTIFICATION_FOLLOW_UP_SAVE_RESPONSE,
    PERMIT_NOTIFICATION_FOLLOW_UP_UPLOAD_ATTACHMENT,
    PERMIT_NOTIFICATION_FOLLOW_UP_SUBMIT_RESPONSE,
    PERMIT_NOTIFICATION_FOLLOW_UP_SAVE_REVIEW_DECISION,
    PERMIT_NOTIFICATION_FOLLOW_UP_NOTIFY_OPERATOR_FOR_DECISION,
    PERMIT_NOTIFICATION_FOLLOW_UP_RETURN_FOR_AMENDS,
    PERMIT_NOTIFICATION_FOLLOW_UP_RECALL_FROM_AMENDS,
    PERMIT_NOTIFICATION_FOLLOW_UP_SAVE_APPLICATION_AMEND,
    PERMIT_NOTIFICATION_FOLLOW_UP_SUBMIT_APPLICATION_AMEND,

    // Permit variation
    PERMIT_VARIATION_OPERATOR_SAVE_APPLICATION,
    PERMIT_VARIATION_UPLOAD_SECTION_ATTACHMENT,
    PERMIT_VARIATION_OPERATOR_SUBMIT_APPLICATION,
    PERMIT_VARIATION_SAVE_APPLICATION_REVIEW,
    PERMIT_VARIATION_SAVE_REVIEW_GROUP_DECISION,
    PERMIT_VARIATION_SAVE_DETAILS_REVIEW_GROUP_DECISION,
    PERMIT_VARIATION_UPLOAD_REVIEW_GROUP_DECISION_ATTACHMENT,
    PERMIT_VARIATION_SAVE_REVIEW_DETERMINATION,
    PERMIT_VARIATION_CANCEL_APPLICATION,

    // AER application
    AER_SAVE_APPLICATION,
    AER_UPLOAD_SECTION_ATTACHMENT,

    // rfi
    RFI_SUBMIT,
    RFI_UPLOAD_ATTACHMENT,
    RFI_RESPONSE_SUBMIT,
    RFI_CANCEL,

    // Request for Determination Extension (RDE)
    RDE_SUBMIT,
    RDE_RESPONSE_SUBMIT,
    RDE_FORCE_DECISION,
    RDE_UPLOAD_ATTACHMENT,

    // payment related task actions
    PAYMENT_MARK_AS_PAID,
    PAYMENT_MARK_AS_RECEIVED,
    PAYMENT_PAY_BY_CARD,
    PAYMENT_CANCEL
    ;
    
    public static Set<RequestTaskActionType> getRequestPeerReviewTypes() {
        return Stream.of(RequestTaskActionType.values())
            .filter(requestTaskActionType -> requestTaskActionType.name().endsWith("REQUEST_PEER_REVIEW"))
            .collect(Collectors.toSet());
    }

    public static Set<RequestTaskActionType> getNotifyOperatorForDecisionTypes() {
        return Stream.of(RequestTaskActionType.values())
            .filter(requestTaskActionType -> requestTaskActionType.name().endsWith("NOTIFY_OPERATOR_FOR_DECISION"))
            .collect(Collectors.toSet());
    }

    public static Set<RequestTaskActionType> getRfiRdeSubmissionTypes() {
        return Set.of(RFI_SUBMIT, RDE_SUBMIT);
    }

    public static List<RequestTaskActionType> getMakePaymentAllowedTypes() {
        return List.of(PAYMENT_MARK_AS_PAID, PAYMENT_PAY_BY_CARD);
    }

    public static List<RequestTaskActionType> getTrackAndConfirmPaymentAllowedTypes() {
        return List.of(PAYMENT_MARK_AS_RECEIVED, PAYMENT_CANCEL);
    }
}
