package uk.gov.pmrv.api.workflow.request.core.domain.enumeration;

/**
 * Request Action Types.
 */
public enum RequestActionType {

    // Installation Account relevant request actions
    INSTALLATION_ACCOUNT_OPENING_APPLICATION_SUBMITTED,
    INSTALLATION_ACCOUNT_OPENING_ACCEPTED,
    INSTALLATION_ACCOUNT_OPENING_REJECTED,
    INSTALLATION_ACCOUNT_OPENING_ACCOUNT_APPROVED,

    // Permit Issuance relevant action types
    PERMIT_ISSUANCE_APPLICATION_SUBMITTED,
    PERMIT_ISSUANCE_APPLICATION_GRANTED,
    PERMIT_ISSUANCE_APPLICATION_REJECTED,
    PERMIT_ISSUANCE_APPLICATION_DEEMED_WITHDRAWN,
    PERMIT_ISSUANCE_PEER_REVIEW_REQUESTED,
    PERMIT_ISSUANCE_APPLICATION_RETURNED_FOR_AMENDS,
    PERMIT_ISSUANCE_APPLICATION_PEER_REVIEWER_ACCEPTED,
    PERMIT_ISSUANCE_APPLICATION_PEER_REVIEWER_REJECTED,
    PERMIT_ISSUANCE_RECALLED_FROM_AMENDS,
    PERMIT_ISSUANCE_APPLICATION_AMENDS_SUBMITTED,

    // permit surrender
    PERMIT_SURRENDER_APPLICATION_SUBMITTED,
    PERMIT_SURRENDER_APPLICATION_GRANTED,
    PERMIT_SURRENDER_APPLICATION_REJECTED,
    PERMIT_SURRENDER_APPLICATION_DEEMED_WITHDRAWN,
    PERMIT_SURRENDER_APPLICATION_CANCELLED,
    PERMIT_SURRENDER_PEER_REVIEW_REQUESTED,
    PERMIT_SURRENDER_APPLICATION_PEER_REVIEWER_ACCEPTED,
    PERMIT_SURRENDER_APPLICATION_PEER_REVIEWER_REJECTED,
    PERMIT_SURRENDER_CESSATION_COMPLETED,

    // Permit notification
    PERMIT_NOTIFICATION_APPLICATION_SUBMITTED,
    PERMIT_NOTIFICATION_APPLICATION_GRANTED,
    PERMIT_NOTIFICATION_APPLICATION_REJECTED,
    PERMIT_NOTIFICATION_APPLICATION_CANCELLED,
    PERMIT_NOTIFICATION_PEER_REVIEW_REQUESTED,
    PERMIT_NOTIFICATION_APPLICATION_PEER_REVIEWER_ACCEPTED,
    PERMIT_NOTIFICATION_APPLICATION_PEER_REVIEWER_REJECTED,
    PERMIT_NOTIFICATION_FOLLOW_UP_DATE_EXTENDED,
    PERMIT_NOTIFICATION_FOLLOW_UP_RESPONSE_SUBMITTED,
    PERMIT_NOTIFICATION_APPLICATION_COMPLETED,
    PERMIT_NOTIFICATION_FOLLOW_UP_RETURNED_FOR_AMENDS,
    PERMIT_NOTIFICATION_FOLLOW_UP_RECALLED_FROM_AMENDS,
    PERMIT_NOTIFICATION_FOLLOW_UP_APPLICATION_AMENDS_SUBMITTED,

    // permit revocation
    PERMIT_REVOCATION_APPLICATION_SUBMITTED,
    PERMIT_REVOCATION_APPLICATION_CANCELLED,
    PERMIT_REVOCATION_PEER_REVIEW_REQUESTED,
    PERMIT_REVOCATION_APPLICATION_PEER_REVIEWER_ACCEPTED,
    PERMIT_REVOCATION_APPLICATION_PEER_REVIEWER_REJECTED,
    PERMIT_REVOCATION_APPLICATION_WITHDRAWN,
    PERMIT_REVOCATION_CESSATION_COMPLETED,
    
    // permit variation
    PERMIT_VARIATION_APPLICATION_SUBMITTED,
    PERMIT_VARIATION_APPLICATION_CANCELLED,
    
    // rfi
    RFI_SUBMITTED,
    RFI_CANCELLED,
    RFI_EXPIRED,
    RFI_RESPONSE_SUBMITTED,

    // Request for Determination Extension (RDE)
    RDE_SUBMITTED,
    RDE_ACCEPTED,
    RDE_REJECTED,
    RDE_FORCE_ACCEPTED,
    RDE_FORCE_REJECTED,
    RDE_EXPIRED,
    RDE_CANCELLED,

    //payment related request actions
    PAYMENT_MARKED_AS_PAID,
    PAYMENT_MARKED_AS_RECEIVED,
    PAYMENT_COMPLETED,
    PAYMENT_CANCELLED,

    // common action type for requests terminated by the system
    REQUEST_TERMINATED
}
