package uk.gov.pmrv.api.workflow.request.core.domain.enumeration;

public enum RequestTaskPayloadType {

    INSTALLATION_ACCOUNT_OPENING_APPLICATION_PAYLOAD,
    
    PERMIT_ISSUANCE_APPLICATION_SUBMIT_PAYLOAD,
    PERMIT_ISSUANCE_APPLICATION_REVIEW_PAYLOAD,
    PERMIT_ISSUANCE_APPLICATION_PEER_REVIEW_PAYLOAD,
    PERMIT_ISSUANCE_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    PERMIT_ISSUANCE_APPLICATION_AMENDS_SUBMIT_PAYLOAD,
    PERMIT_ISSUANCE_WAIT_FOR_AMENDS_PAYLOAD,
    
    PERMIT_SURRENDER_APPLICATION_SUBMIT_PAYLOAD,
    PERMIT_SURRENDER_APPLICATION_REVIEW_PAYLOAD,
    PERMIT_SURRENDER_APPLICATION_PEER_REVIEW_PAYLOAD,
    PERMIT_SURRENDER_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    PERMIT_SURRENDER_CESSATION_SUBMIT_PAYLOAD,
    
    PERMIT_REVOCATION_APPLICATION_SUBMIT_PAYLOAD,
    PERMIT_REVOCATION_APPLICATION_PEER_REVIEW_PAYLOAD,
    PERMIT_REVOCATION_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    PERMIT_REVOCATION_WAIT_FOR_APPEAL_PAYLOAD,
    PERMIT_REVOCATION_CESSATION_SUBMIT_PAYLOAD,
    
    PERMIT_NOTIFICATION_APPLICATION_SUBMIT_PAYLOAD,
    PERMIT_NOTIFICATION_APPLICATION_REVIEW_PAYLOAD,
    PERMIT_NOTIFICATION_APPLICATION_PEER_REVIEW_PAYLOAD,
    PERMIT_NOTIFICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    PERMIT_NOTIFICATION_FOLLOW_UP_PAYLOAD,
    PERMIT_NOTIFICATION_WAIT_FOR_FOLLOW_UP_PAYLOAD,
    PERMIT_NOTIFICATION_FOLLOW_UP_APPLICATION_REVIEW_PAYLOAD,
    PERMIT_NOTIFICATION_FOLLOW_UP_APPLICATION_AMENDS_SUBMIT_PAYLOAD,
    PERMIT_NOTIFICATION_FOLLOW_UP_WAIT_FOR_AMENDS_PAYLOAD,

    AER_APPLICATION_SUBMIT_PAYLOAD,
    
    PERMIT_VARIATION_APPLICATION_SUBMIT_PAYLOAD,
    PERMIT_VARIATION_APPLICATION_REVIEW_PAYLOAD,
    
    RFI_RESPONSE_SUBMIT_PAYLOAD,
    
    RDE_RESPONSE_SUBMIT_PAYLOAD,
    RDE_WAIT_FOR_RESPONSE_PAYLOAD,

    PAYMENT_MAKE_PAYLOAD,
    PAYMENT_TRACK_PAYLOAD,
    PAYMENT_CONFIRM_PAYLOAD,

    SYSTEM_MESSAGE_NOTIFICATION_PAYLOAD
}
