package uk.gov.pmrv.api.permit.domain.sourcestreams;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum SourceStreamType {

    NON_FERROUS_SEC_ALUMINIUM_MASS_BALANCE_METHODOLOGY,
    NON_FERROUS_SEC_ALUMINIUM_PROCESS_EMISSIONS,
    AMMONIA_FUEL_AS_PROCESS_INPUT,
    BULK_ORGANIC_CHEMICALS_MASS_BALANCE_METHODOLOGY,
    CARBON_BLACK_MASS_BALANCE_METHODOLOGY,
    CEMENT_CLINKER_CKD,
    CEMENT_CLINKER_CLINKER_OUTPUT_METHOD_B,
    CEMENT_CLINKER_KILN_INPUT_BASED_METHOD_A,
    CEMENT_CLINKER_NON_CARBONATE_CARBON,
    CERAMICS_ALKALI_OXIDE_METHOD_B,
    CERAMICS_CARBON_INPUTS_METHOD_A,
    CERAMICS_SCRUBBING,
    COKE_CARBONATE_INPUT_METHOD_A,
    COKE_FUEL_AS_PROCESS_INPUT,
    COKE_MASS_BALANCE,
    COKE_OXIDE_OUTPUT_METHOD_B,
    COMBUSTION_COMMERCIAL_STANDARD_FUELS,
    COMBUSTION_FLARES,
    COMBUSTION_GAS_PROCESSING_TERMINALS,
    COMBUSTION_OTHER_GASEOUS_LIQUID_FUELS,
    COMBUSTION_SCRUBBING_CARBONATE,
    COMBUSTION_SCRUBBING_GYPSUM,
    COMBUSTION_SOLID_FUELS,
    GLASS_AND_MINERAL_WOOL_CARBONATES_INPUT,
    HYDROGEN_AND_SYNTHESIS_GAS_FUEL_AS_PROCESS_INPUT,
    HYDROGEN_AND_SYNTHESIS_GAS_MASS_BALANCE_METHODOLOGY,
    IRON_STEEL_CARBONATE_INPUT,
    IRON_STEEL_FUEL_AS_PROCESS_INPUT,
    IRON_STEEL_MASS_BALANCE,
    LIME_DOLOMITE_MAGNESITE_ALKALI_EARTH_OXIDE_METHOD_B,
    LIME_DOLOMITE_MAGNESITE_CARBONATES_METHOD_A,
    LIME_DOLOMITE_MAGNESITE_KILN_DUST_METHOD_B,
    METAL_ORE_CARBONATE_INPUT,
    METAL_ORE_MASS_BALANCE,
    OTHER,
    PRIMARY_ALUMINIUM_MASS_BALANCE_METHODOLOGY,
    PRIMARY_ALUMINIUM_PFC_EMISSIONS_OVERVOLTAGE_METHOD,
    PRIMARY_ALUMINIUM_PFC_EMISSIONS_SLOPE_METHOD,
    PULP_PAPER_MAKE_UP_CHEMICALS,
    REFINERIES_CATALYTIC_CRACKER_REGENERATION,
    REFINERIES_HYDROGEN_PRODUCTION,
    REFINERIES_MASS_BALANCE,
    SODA_ASH_SODIUM_BICARBONATE_MASS_BALANCE_METHODOLOGY
    ;

}
