import {
  CalculationMonitoringApproach,
  CoordinatesDTO,
  InstallationOperatorDetails,
  MonitoringReporting,
  PermitIssuanceApplicationSubmitRequestTaskPayload,
  PFCMonitoringApproach,
  SourceStream,
  TransferredCO2MonitoringApproach,
} from 'pmrv-api';

export const mockOnshore = {
  companyReferenceNumber: '88888',
  installationLocation: {
    type: 'ONSHORE',
    address: {
      line1: 'Korinthou 4, Neo Psychiko',
      line2: 'line 2 legal test',
      city: 'Athens',
      country: 'GR',
      postcode: '15452',
    },
    gridReference: 'NN166712',
  },
  installationName: 'onshore permit installation',
  operator: 'onshore permit',
  operatorDetailsAddress: {
    line1: 'Korinthou 3, Neo Psychiko',
    line2: 'line 2 legal test',
    city: 'Athens',
    country: 'GR',
    postcode: '15451',
  },
  operatorType: 'LIMITED_COMPANY',
  siteName: 'site name',
} as InstallationOperatorDetails;

export const mockOffshore = {
  companyReferenceNumber: '88888',
  installationLocation: {
    type: 'OFFSHORE',
    latitude: { degree: 12, minute: 3, second: 45, cardinalDirection: 'NORTH' as CoordinatesDTO['cardinalDirection'] },
    longitude: { degree: 6, minute: 12, second: 2, cardinalDirection: 'WEST' as CoordinatesDTO['cardinalDirection'] },
  },
  installationName: 'onshore permit installation',
  operator: 'onshore permit',
  operatorDetailsAddress: {
    line1: 'Korinthou 3, Neo Psychiko',
    line2: 'line 2 legal test',
    city: 'Athens',
    country: 'GR',
    postcode: '15451',
  },
  operatorType: 'LIMITED_COMPANY',
  siteName: 'site name',
} as InstallationOperatorDetails;

export const monitoringRolesPayload: MonitoringReporting = {
  monitoringRoles: [
    { jobTitle: 'Test job', mainDuties: 'Testing' },
    { jobTitle: 'Check job', mainDuties: 'Checking' },
  ],
  organisationCharts: ['abc'],
};

export const sourceStreamsPayload: SourceStream[] = [
  {
    description: 'WHITE_SPIRIT_SBP',
    id: '16236817394240.1574963093314663',
    reference: '13123124',
    type: 'REFINERIES_HYDROGEN_PRODUCTION',
  },
  {
    description: 'LIGNITE',
    id: '16236830126010.5957932377356623',
    reference: '33334',
    type: 'REFINERIES_CATALYTIC_CRACKER_REGENERATION',
  },
  {
    description: 'OTHER',
    otherDescriptionName: 'Other Description',
    id: '16236830126010.5957932377356624',
    reference: '33334',
    type: 'REFINERIES_CATALYTIC_CRACKER_REGENERATION',
  },
];

export const mockPermitApplyPayload: PermitIssuanceApplicationSubmitRequestTaskPayload = {
  permitSectionsCompleted: {
    sourceStreams: [false],
    managementProceduresExist: [true],
    assignmentOfResponsibilities: [true],
    estimatedAnnualEmissions: [true],
    environmentalPermitsAndLicences: [true],
    installationDescription: [true],
    regulatedActivities: [true],
  },
  permitAttachments: {
    '2c30c8bf-3d5e-474d-98a0-123a87eb60dd': 'cover.jpg',
    '60fe9548-ac65-492a-b057-60033b0fbbea': 'PublicationAgreement.pdf',
    '6e52fd76-4416-4f1f-b7c6-c07b3231d075': 'samplingPlan.pdf',
    '743ba2e6-35c1-4181-b2fd-6a648361d691': 'uncertainty.pdf',
  },
  payloadType: 'PERMIT_ISSUANCE_APPLICATION_SUBMIT_PAYLOAD',
  installationOperatorDetails: mockOnshore,
  permit: {
    abbreviations: {
      exist: true,
      abbreviationDefinitions: [
        {
          abbreviation: 'Mr',
          definition: 'Mister',
        },
        {
          abbreviation: 'Ms',
          definition: 'Miss',
        },
      ],
    },
    additionalDocuments: {
      exist: true,
      documents: ['2c30c8bf-3d5e-474d-98a0-123a87eb60dd', '60fe9548-ac65-492a-b057-60033b0fbbea'],
    },
    assessAndControlRisk: null,
    confidentialityStatement: {
      exist: true,
      confidentialSections: [
        {
          section: 'Section 1',
          explanation: 'Explanation 1',
        },
        {
          section: 'Section 2',
          explanation: 'Explanation 2',
        },
      ],
    },
    controlOfOutsourcedActivities: null,
    correctionsAndCorrectiveActions: null,
    dataFlowActivities: {
      appliedStandards: 'Standards',
      itSystemUsed: 'asdas',
      locationOfRecords: 'Location',
      procedureDescription: 'sadas',
      procedureDocumentName: 'Amazing',
      procedureReference: 'Ref',
      diagramReference: null,
      responsibleDepartmentOrRole: 'Department',
      primaryDataSources: 'Primary data sources',
      processingSteps: 'Processing steps',
    },
    environmentalManagementSystem: {
      exist: true,
      certified: true,
      certificationStandard: 'BS EN ISO14001: 2014',
    },
    environmentalPermitsAndLicences: {
      envPermitOrLicences: [
        {
          issuingAuthority: 'FWW',
          num: '1234',
          permitHolder: 'GovUK',
          type: 'Environmental Protection Regulations',
        },
        {
          issuingAuthority: 'Peacegreen',
          num: '1253',
          permitHolder: 'GovUK',
          type: 'Seaside Regulations',
        },
      ],
      exist: true,
    },
    estimatedAnnualEmissions: {
      quantity: 33,
    },
    installationDescription: {
      mainActivitiesDesc: 'Activities tests',
      siteDescription: 'Site description',
    },
    monitoringMethodologyPlans: { exist: false },
    managementProceduresExist: true,
    monitoringReporting: null,
    qaDataFlowActivities: null,
    qaMeteringAndMeasuringEquipment: null,
    recordKeepingAndDocumentation: null,
    reviewAndValidationOfData: null,
    siteDiagrams: ['abc'],
    assignmentOfResponsibilities: {
      appliedStandards: 'Standards',
      itSystemUsed: 'asdas',
      locationOfRecords: 'Location',
      procedureDescription: 'sadas',
      procedureDocumentName: 'Amazing',
      procedureReference: 'Ref',
      responsibleDepartmentOrRole: 'Department',
    },
    monitoringPlanAppropriateness: {
      appliedStandards: 'plan standards',
      itSystemUsed: 'it plan',
      locationOfRecords: 'Location plan',
      procedureDescription: 'sadas plan',
      procedureDocumentName: 'AmazingPlan',
      procedureReference: 'PlanRef',
      responsibleDepartmentOrRole: 'PlanDepartment',
    },
    emissionPoints: [
      {
        description: 'Emission point 1',
        id: '16363790610230.8369404469603225',
        reference: 'The big Ref',
      },
      {
        description: 'Point taken!',
        id: '16236830126010.5957932377356623',
        reference: 'Yet another reference',
      },
    ],
    emissionSources: [
      {
        description: 'Boiler',
        id: '16245246343280.27155194483385103',
        reference: 'S1',
      },
      {
        description: 'Boiler 2',
        id: '16245287634950.8123179433871819',
        reference: 'S2',
      },
    ],
    emissionSummaries: [
      {
        sourceStream: '16236817394240.1574963093314663',
        emissionPoints: ['16363790610230.8369404469603225', '16236830126010.5957932377356623'],
        emissionSources: ['16245246343280.27155194483385103', '16245287634950.8123179433871819'],
        regulatedActivity: '16236817394240.1574963093314664',
      },
    ],
    measurementDevicesOrMethods: [
      {
        id: '16236817394240.1574963093314700',
        reference: 'ref1',
        type: 'ULTRASONIC_METER',
        measurementRange: '3',
        meteringRangeUnits: 'litres',
        specifiedUncertaintyPercentage: 2.0,
        location: 'north terminal',
        uncertaintySpecified: true,
      },
      {
        id: '16236817394240.1574963093314800',
        reference: 'ref2',
        type: 'ULTRASONIC_METER',
        measurementRange: '3',
        meteringRangeUnits: 'litres',
        location: 'north terminal',
        uncertaintySpecified: false,
      },
    ],
    regulatedActivities: [
      {
        id: '16236817394240.1574963093314664',
        type: 'COMBUSTION',
        capacity: 34344,
        capacityUnit: 'MW_TH',
      },
      {
        id: '16236817394240.1574963093314665',
        type: 'MINERAL_OIL_REFINING',
        capacity: 34345,
        capacityUnit: 'MW',
      },
    ],
    sourceStreams: [
      {
        description: 'WHITE_SPIRIT_SBP',
        id: '16236817394240.1574963093314663',
        reference: '13123124',
        type: 'REFINERIES_HYDROGEN_PRODUCTION',
      },
      {
        description: 'LIGNITE',
        id: '16236830126010.5957932377356623',
        reference: '33334',
        type: 'REFINERIES_CATALYTIC_CRACKER_REGENERATION',
      },
    ],
    monitoringApproaches: {
      CALCULATION: {
        type: 'CALCULATION',
        approachDescription: 'Calculation approach description',
        samplingPlan: {
          exist: true,
          details: {
            analysis: {
              procedureDescription: 'Sampling analysis procedure description',
              procedureDocumentName: 'Sampling analysis procedure document name',
              procedureReference: 'Sampling analysis procedure procedure reference',
              responsibleDepartmentOrRole: 'Sampling analysis responsible department',
              locationOfRecords: 'Sampling analysis location of records',
              appliedStandards: 'Sampling analysis applied standards',
              diagramReference: 'Sampling analysis reference',
              itSystemUsed: 'Sampling analysis it system',
            },
            procedurePlan: {
              appliedStandards: 'Plan standards',
              diagramReference: 'Plan reference',
              itSystemUsed: 'Plan it',
              procedureDescription: 'pro1',
              procedureDocumentName: 'pro1',
              procedureReference: 'pro1',
              responsibleDepartmentOrRole: 'pro1',
              locationOfRecords: 'pro1',
              procedurePlanIds: ['6e52fd76-4416-4f1f-b7c6-c07b3231d075'],
            },
            appropriateness: {
              appliedStandards: 'Appropriateness standards',
              diagramReference: 'Appropriateness reference',
              itSystemUsed: 'Appropriateness it',
              procedureDescription: 'Appropriateness description',
              procedureDocumentName: 'Appropriateness name',
              procedureReference: 'Appropriateness proc ref',
              responsibleDepartmentOrRole: 'Appropriateness department',
              locationOfRecords: 'Appropriateness location',
            },
            yearEndReconciliation: {
              exist: true,
              procedureForm: {
                appliedStandards: 'Reconciliation standards',
                diagramReference: 'Reconciliation reference',
                itSystemUsed: 'Reconciliation it',
                procedureDescription: 'Reconciliation description',
                procedureDocumentName: 'Reconciliation name',
                procedureReference: 'Reconciliation proc ref',
                responsibleDepartmentOrRole: 'Reconciliation department',
                locationOfRecords: 'Reconciliation location',
              },
            },
          },
        },
        sourceStreamCategoryAppliedTiers: [
          {
            sourceStreamCategory: {
              sourceStream: '16236817394240.1574963093314663',
              emissionSources: ['16245246343280.27155194483385103'],
              annualEmittedCO2Tonnes: 23.5,
              calculationMethod: 'STANDARD',
              categoryType: 'MAJOR',
            },
          },
        ],
      } as CalculationMonitoringApproach,
      PFC: {
        type: 'PFC',
        approachDescription: 'PFC approach description',
        cellAndAnodeTypes: [
          {
            cellType: 'cell type one',
            anodeType: 'anode type one',
          },
        ],
        collectionEfficiency: {
          procedureDescription: 'procedureDescription',
          procedureDocumentName: 'procedureDocumentName',
          procedureReference: 'procedureReference',
          diagramReference: 'diagramReference',
          responsibleDepartmentOrRole: 'responsibleDepartmentOrRole',
          locationOfRecords: 'locationOfRecords',
          itSystemUsed: 'itSystemUsed',
          appliedStandards: 'appliedStandards',
        },
        tier2EmissionFactor: {
          exist: true,
          determinationInstallation: {
            procedureDescription: 'procedureDescription1',
            procedureDocumentName: 'procedureDocumentName1',
            procedureReference: 'procedureReference1',
            responsibleDepartmentOrRole: 'responsibleDepartmentOrRole1',
            locationOfRecords: 'locationOfRecords1',
          },
          scheduleMeasurements: {
            procedureDescription: 'procedureDescription2',
            procedureDocumentName: 'procedureDocumentName2',
            procedureReference: 'procedureReference2',
            responsibleDepartmentOrRole: 'responsibleDepartmentOrRole2',
            locationOfRecords: 'locationOfRecords2',
          },
        },
        sourceStreamCategoryAppliedTiers: [
          {
            sourceStreamCategory: {
              sourceStream: '16236817394240.1574963093314663',
              emissionSources: ['16245246343280.27155194483385103'],
              emissionPoints: ['16363790610230.8369404469603225'],
              annualEmittedCO2Tonnes: 23.5,
              calculationMethod: 'OVERVOLTAGE',
              categoryType: 'MAJOR',
            },
          },
        ],
      } as any,
      N2O: {
        type: 'N2O',
        approachDescription: 'test',
        emissionDetermination: {
          procedureDescription: 'procedureDescription',
          procedureDocumentName: 'procedureDocumentName',
          procedureReference: 'procedureReference',
          diagramReference: 'diagramReference',
          responsibleDepartmentOrRole: 'responsibleDepartmentOrRole',
          locationOfRecords: 'locationOfRecords',
          itSystemUsed: 'itSystemUsed',
          appliedStandards: 'appliedStandards',
        },
        gasFlowCalculation: {
          exist: true,
          procedureForm: {
            procedureDescription: 'procedureDescription',
            procedureDocumentName: 'procedureDocumentName',
            procedureReference: 'procedureReference',
            diagramReference: 'diagramReference',
            responsibleDepartmentOrRole: 'responsibleDepartmentOrRole',
            locationOfRecords: 'locationOfRecords',
            itSystemUsed: 'itSystemUsed',
            appliedStandards: 'appliedStandards',
          },
        },
        sourceStreamCategoryAppliedTiers: [
          {
            sourceStreamCategory: {
              sourceStream: '16236817394240.1574963093314663',
              emissionSources: ['16245246343280.27155194483385103'],
              emissionPoints: ['16363790610230.8369404469603225'],
              emissionType: 'ABATED',
              monitoringApproachType: 'CALCULATION',
              annualEmittedCO2Tonnes: 23.5,
              categoryType: 'MAJOR',
            },
            appliedStandard: {
              parameter: 'param1',
              appliedStandard: 'standard1',
              deviationFromAppliedStandardExist: true,
              deviationFromAppliedStandardDetails: 'deviation1',
              laboratoryName: 'lab1',
              laboratoryAccredited: false,
              laboratoryAccreditationEvidence: 'labEvidence',
            },
          },
        ],
      } as any,
      INHERENT_CO2: {
        type: 'INHERENT_CO2',
        approachDescription: 'test',
      } as any,
      TRANSFERRED_CO2: {
        type: 'TRANSFERRED_CO2',
        receivingTransferringInstallations: [
          {
            type: 'RECEIVING',
            installationIdentificationCode: 'code1',
            operator: 'operator1',
            installationName: 'name1',
            co2source: 'source1',
          },
        ],
        accountingEmissions: {
          chemicallyBound: false,
          accountingEmissionsDetails: {
            measurementDevicesOrMethods: ['16236817394240.1574963093314700'],
            samplingFrequency: 'DAILY',
            tier: 'TIER_4',
          },
        },
        temperaturePressure: {
          exist: true,
          measurementDevices: [
            {
              reference: 'reference1',
              type: 'OTHER',
              otherTypeName: 'otherTypeName1',
              location: 'location1',
            },
            {
              reference: 'reference2',
              type: 'BALANCE',
              location: 'location2',
            },
          ],
        },
        deductionsToAmountOfTransferredCO2: {
          exist: true,
          procedureForm: {
            appliedStandards: 'appliedStandards',
            diagramReference: 'diagramReference',
            itSystemUsed: 'itSystemUsed',
            locationOfRecords: 'locationOfRecords',
            procedureDescription: 'procedureDescription',
            procedureDocumentName: 'procedureDocumentName',
            procedureReference: 'procedureReference',
            responsibleDepartmentOrRole: 'responsibleDepartmentOrRole',
          },
        },
        transferOfCO2: {
          procedureDescription: 'procedureDescription',
          procedureDocumentName: 'procedureDocumentName',
          procedureReference: 'procedureReference',
          diagramReference: 'diagramReference',
          responsibleDepartmentOrRole: 'responsibleDepartmentOrRole',
          locationOfRecords: 'locationOfRecords',
          itSystemUsed: 'itSystemUsed',
          appliedStandards: 'appliedStandards',
        },
        approachDescription: 'test',
      } as any,
      FALLBACK: {
        type: 'FALLBACK',
        approachDescription: 'Fallback monitoring approach description',
        justification: 'Fallback monitoring approach justification',
        annualUncertaintyAnalysis: {
          locationOfRecords: 'locationOfRecords',
          procedureDescription: 'procedureDescription',
          procedureDocumentName: 'procedureDocumentName',
          procedureReference: 'procedureReference',
          responsibleDepartmentOrRole: 'responsibleDepartmentOrRole',
          appliedStandards: null,
          diagramReference: null,
          itSystemUsed: null,
        },
        sourceStreamCategoryAppliedTiers: [
          {
            sourceStreamCategory: {
              sourceStream: '16236817394240.1574963093314663',
              emissionSources: ['16245246343280.27155194483385103'],
              measurementDevicesOrMethods: ['16236817394240.1574963093314700'],
              annualEmittedCO2Tonnes: 23.8,
              categoryType: 'MAJOR',
            },
          },
        ],
      } as any,
      MEASUREMENT: {
        type: 'MEASUREMENT',
        approachDescription: 'Measurement monitoring approach description',
        emissionDetermination: {
          procedureDescription: 'procedureDescription',
          procedureDocumentName: 'procedureDocumentName',
          procedureReference: 'procedureReference',
          diagramReference: 'diagramReference',
          responsibleDepartmentOrRole: 'responsibleDepartmentOrRole',
          locationOfRecords: 'locationOfRecords',
          itSystemUsed: 'itSystemUsed',
          appliedStandards: 'appliedStandards',
        },
        gasFlowCalculation: {
          exist: true,
          procedureForm: {
            appliedStandards: 'appliedStandards',
            diagramReference: 'diagramReference',
            itSystemUsed: 'itSystemUsed',
            locationOfRecords: 'locationOfRecords',
            procedureDescription: 'procedureDescription',
            procedureDocumentName: 'procedureDocumentName',
            procedureReference: 'procedureReference',
            responsibleDepartmentOrRole: 'responsibleDepartmentOrRole',
          },
        },
        sourceStreamCategoryAppliedTiers: [
          {
            sourceStreamCategory: {
              sourceStream: '16236817394240.1574963093314663',
              emissionSources: ['16245246343280.27155194483385103'],
              emissionPoints: ['16363790610230.8369404469603225'],
              annualEmittedCO2Tonnes: 23.8,
              categoryType: 'MAJOR',
            },
            appliedStandard: {
              parameter: 'param1',
              appliedStandard: 'standard1',
              deviationFromAppliedStandardExist: true,
              deviationFromAppliedStandardDetails: 'deviation1',
              laboratoryName: 'lab1',
              laboratoryAccredited: false,
              laboratoryAccreditationEvidence: 'labEvidence',
            },
          },
        ],
      } as any,
    },
    uncertaintyAnalysis: {
      exist: true,
      attachments: ['743ba2e6-35c1-4181-b2fd-6a648361d691'],
    },
  },
};

export const mockPermitCompletePayload: PermitIssuanceApplicationSubmitRequestTaskPayload = {
  payloadType: 'PERMIT_ISSUANCE_APPLICATION_SUBMIT_PAYLOAD',
  permit: {
    environmentalPermitsAndLicences: {
      exist: true,
      envPermitOrLicences: [
        {
          type: '2342',
          num: '23423',
          issuingAuthority: '24234',
          permitHolder: '23423',
        },
      ],
    },
    estimatedAnnualEmissions: {
      quantity: 333,
    },
    installationDescription: {
      mainActivitiesDesc: 'gyjgfh',
      siteDescription: 'Site description',
    },
    regulatedActivities: [
      {
        id: '16285909970300.1344282727316457',
        type: 'COMBUSTION',
        capacity: 345,
        capacityUnit: 'KW_TH',
      },
      {
        id: '16285909970300.5268380326820965',
        type: 'MINERAL_OIL_REFINING',
        capacity: 5555,
        capacityUnit: 'MW_TH',
      },
    ],
    assessAndControlRisk: {
      procedureDescription: 'sdf',
      procedureDocumentName: 'sdfsdf',
      procedureReference: 'sdfsdf',
      diagramReference: 'sdf',
      responsibleDepartmentOrRole: 'sdf',
      locationOfRecords: 'sdf',
      itSystemUsed: 'sdf',
      appliedStandards: 'sdf',
    },
    assignmentOfResponsibilities: {
      procedureDescription: 'dfds',
      procedureDocumentName: 'sdf',
      procedureReference: 'sdf',
      diagramReference: 'sdf',
      responsibleDepartmentOrRole: 'sdf',
      locationOfRecords: 'sdf',
      itSystemUsed: 'sdf',
      appliedStandards: 'sdf',
    },
    controlOfOutsourcedActivities: {
      procedureDescription: 'sdfd',
      procedureDocumentName: 'sdf',
      procedureReference: 'sdf',
      diagramReference: 'sdf',
      responsibleDepartmentOrRole: 'sdf',
      locationOfRecords: 'sdf',
      itSystemUsed: 'sdf',
      appliedStandards: 'sdf',
    },
    correctionsAndCorrectiveActions: {
      procedureDescription: 'sdfsd',
      procedureDocumentName: 'sads',
      procedureReference: 'sdf',
      diagramReference: 'asdas',
      responsibleDepartmentOrRole: '345345',
      locationOfRecords: 'sdf',
      itSystemUsed: '34534',
      appliedStandards: 'sdfsd',
    },
    monitoringPlanAppropriateness: {
      procedureDescription: 'sdfs',
      procedureDocumentName: 'sdf',
      procedureReference: 'sdf',
      diagramReference: 'sdf',
      responsibleDepartmentOrRole: 'sdf',
      locationOfRecords: 'sdf',
      itSystemUsed: 'sdf',
      appliedStandards: 'sdf',
    },
    qaDataFlowActivities: {
      procedureDescription: 'sdas',
      procedureDocumentName: 'sads',
      procedureReference: 'cvbcvb',
      diagramReference: 'sdf',
      responsibleDepartmentOrRole: 'sdf',
      locationOfRecords: 'sdf',
      itSystemUsed: 'sdf',
      appliedStandards: 'sdf',
    },
    qaMeteringAndMeasuringEquipment: {
      procedureDescription: 'sdas',
      procedureDocumentName: 'sdf',
      procedureReference: 'cvbcvb',
      diagramReference: 'sdf',
      responsibleDepartmentOrRole: 'asd',
      locationOfRecords: 'asdas',
      itSystemUsed: 'asda',
      appliedStandards: 'asd',
    },
    recordKeepingAndDocumentation: {
      procedureDescription: 'sdfsd',
      procedureDocumentName: 'sdf',
      procedureReference: 'asdas',
      diagramReference: 'cbbbb',
      responsibleDepartmentOrRole: '345345',
      locationOfRecords: 'sdf',
      itSystemUsed: 'cvbcvb',
      appliedStandards: 'sdf',
    },
    reviewAndValidationOfData: {
      procedureDescription: 'sdfds',
      procedureDocumentName: 'sdf',
      procedureReference: '234',
      diagramReference: '345',
      responsibleDepartmentOrRole: '345',
      locationOfRecords: 'sdf',
      itSystemUsed: 'cvbcvb',
      appliedStandards: 'sdf',
    },
    monitoringReporting: {
      monitoringRoles: [
        {
          jobTitle: 'Role 1',
          mainDuties: 'dfgdf',
        },
      ],
    },
    dataFlowActivities: {
      procedureDescription: 'asdas',
      procedureDocumentName: 'sdf',
      procedureReference: 'sdf',
      diagramReference: 'asdas',
      responsibleDepartmentOrRole: 'sdf',
      locationOfRecords: '345345',
      itSystemUsed: 'sdf',
      appliedStandards: 'asd',
      primaryDataSources: '34',
      processingSteps: 'asdas',
    },
    environmentalManagementSystem: {
      exist: false,
      certified: false,
    },
    monitoringMethodologyPlans: { exist: false },
    managementProceduresExist: true,
    sourceStreams: [
      {
        id: '16285906590910.6068077459918291',
        reference: 'S1 ',
        description: 'BIOGASOLINE',
        type: 'COKE_OXIDE_OUTPUT_METHOD_B',
      },
    ],
    measurementDevicesOrMethods: [
      {
        id: '16285908517990.09722032531195857',
        reference: 'M1 Meter south boiler 1',
        type: 'VENTURI_METER',
        measurementRange: '3',
        meteringRangeUnits: 'litres',
        uncertaintySpecified: true,
        specifiedUncertaintyPercentage: 2,
        location: 'north terminal',
      },
    ],
    emissionSources: [
      {
        id: '16322182132590.5885074834095196',
        reference: 'S1 ',
        description: 'Boiler',
      },
    ],
    emissionPoints: [
      {
        id: '16285907821090.18383344328435758',
        reference: 'EP1',
        description: 'Emission Point 1',
      },
    ],
    emissionSummaries: [
      {
        sourceStream: '16285906590910.6068077459918291',
        emissionSources: ['16322182132590.5885074834095196'],
        emissionPoints: ['16285907821090.18383344328435758'],
        regulatedActivity: '16285909970300.1344282727316457',
        excludedRegulatedActivity: false,
      },
      {
        sourceStream: '16285906590910.6068077459918291',
        emissionSources: ['16322182132590.5885074834095196'],
        emissionPoints: ['16285907821090.18383344328435758'],
        regulatedActivity: '16285909970300.5268380326820965',
        excludedRegulatedActivity: false,
      },
    ],
    siteDiagrams: ['42cd0cf0-180a-4b0d-bdf7-54619cf95572'],
    abbreviations: {
      exist: false,
    },
    confidentialityStatement: {
      exist: true,
      confidentialSections: [
        {
          section: 'dss',
          explanation: 'sdfs',
        },
      ],
    },
    additionalDocuments: {
      exist: false,
    },
    monitoringApproaches: {
      TRANSFERRED_CO2: {
        type: 'TRANSFERRED_CO2',
        receivingTransferringInstallations: [
          {
            type: 'RECEIVING',
            installationIdentificationCode: '234',
            operator: 'wer',
            installationName: 'wer',
            co2source: 'wer',
          },
        ],
        accountingEmissions: {
          chemicallyBound: true,
        },
        deductionsToAmountOfTransferredCO2: {
          exist: false,
        },
        procedureForLeakageEvents: {
          exist: false,
        },
        temperaturePressure: {
          exist: false,
        },
        transferOfCO2: {
          procedureDescription: 'xcv',
          procedureDocumentName: '345',
          procedureReference: '345',
          diagramReference: '345',
          responsibleDepartmentOrRole: '345',
          locationOfRecords: '345',
          itSystemUsed: '345',
          appliedStandards: '345',
        },
        quantificationMethodologies: {
          procedureDescription: 'dfg',
          procedureDocumentName: '345',
          procedureReference: '345345',
          diagramReference: '345',
          responsibleDepartmentOrRole: '345',
          locationOfRecords: '345',
          itSystemUsed: '345',
          appliedStandards: '345',
        },
        approachDescription: 'sdfsd',
      } as TransferredCO2MonitoringApproach,
      PFC: {
        type: 'PFC',
        approachDescription: 'assdf',
        cellAndAnodeTypes: [
          {
            cellType: 'sdfsdf',
            anodeType: 'sdfds',
          },
        ],
        collectionEfficiency: {
          procedureDescription: 'sdfsd',
          procedureDocumentName: 'sdf',
          procedureReference: 'asdas',
          diagramReference: 'sdf',
          responsibleDepartmentOrRole: 'bcvbcv',
          locationOfRecords: 'asd',
          itSystemUsed: '345',
          appliedStandards: 'sdf',
        },
        sourceStreamCategoryAppliedTiers: [
          {
            sourceStreamCategory: {
              sourceStream: '16285906590910.6068077459918291',
              emissionSources: ['16322182132590.5885074834095196'],
              emissionPoints: ['16285907821090.18383344328435758'],
              annualEmittedCO2Tonnes: 23.5,
              calculationMethod: 'OVERVOLTAGE',
              categoryType: 'MAJOR',
            },
            activityData: {
              massBalanceApproachUsed: true,
              tier: 'TIER_4',
            },
            emissionFactor: {
              tier: 'TIER_2',
            },
          },
        ],
        tier2EmissionFactor: {
          exist: true,
          determinationInstallation: {
            procedureDescription: 'procedureDescription1',
            procedureDocumentName: 'procedureDocumentName1',
            procedureReference: 'procedureReference1',
            responsibleDepartmentOrRole: 'responsibleDepartmentOrRole1',
            locationOfRecords: 'locationOfRecords1',
          },
          scheduleMeasurements: {
            procedureDescription: 'procedureDescription2',
            procedureDocumentName: 'procedureDocumentName2',
            procedureReference: 'procedureReference2',
            responsibleDepartmentOrRole: 'responsibleDepartmentOrRole2',
            locationOfRecords: 'locationOfRecords2',
          },
        },
      } as PFCMonitoringApproach,
      FALLBACK: {
        type: 'FALLBACK',
        approachDescription: 'dsfsdf',
        justification: 'sdfsd',
        annualUncertaintyAnalysis: {
          procedureDescription: 'sdfs',
          procedureDocumentName: '23423',
          procedureReference: 'sdf',
          diagramReference: 'cbbbb',
          responsibleDepartmentOrRole: 'asd',
          locationOfRecords: 'das',
          itSystemUsed: 'asd',
          appliedStandards: 'asd',
        },
        sourceStreamCategoryAppliedTiers: [
          {
            sourceStreamCategory: {
              sourceStream: '16285906590910.6068077459918291',
              emissionSources: ['16322182132590.5885074834095196'],
              measurementDevicesOrMethods: ['16285908517990.09722032531195857'],
              annualEmittedCO2Tonnes: 23.8,
              categoryType: 'MAJOR',
            },
          },
        ],
      } as any,
      INHERENT_CO2: {
        type: 'INHERENT_CO2',
        approachDescription: 'dfsdf',
      } as any,
      N2O: {
        type: 'N2O',
        approachDescription: 'swwerew',
        emissionDetermination: {
          procedureDescription: 'sdfd',
          procedureDocumentName: 'sdf',
          procedureReference: 'sdf',
          diagramReference: 'dfg',
          responsibleDepartmentOrRole: 'asdas',
          locationOfRecords: 'asd',
          itSystemUsed: 'asd',
          appliedStandards: 'dfg',
        },
        referenceDetermination: {
          procedureDescription: 'sdfsd',
          procedureDocumentName: 'sdf',
          procedureReference: 'sdf',
          diagramReference: 'sdf',
          responsibleDepartmentOrRole: 'sdf',
          locationOfRecords: 'asd',
          itSystemUsed: 'sdf',
          appliedStandards: 'sdf',
        },
        operationalManagement: {
          procedureDescription: 'sdfsdf',
          procedureDocumentName: 'sdf',
          procedureReference: 'sdf',
          diagramReference: '345345',
          responsibleDepartmentOrRole: 'asdas',
          locationOfRecords: 'sdf',
          itSystemUsed: 'cvbcvb',
          appliedStandards: 'sdf',
        },
        nitrousOxideEmissionsDetermination: {
          procedureDescription: 'sdfsdf',
          procedureDocumentName: 'sdf',
          procedureReference: '234',
          diagramReference: 'cbbbb',
          responsibleDepartmentOrRole: '345',
          locationOfRecords: 'sdf',
          itSystemUsed: '34534',
          appliedStandards: 'sdf',
        },
        nitrousOxideConcentrationDetermination: {
          procedureDescription: 'asdasd',
          procedureDocumentName: 'sdf',
          procedureReference: 'sdf',
          diagramReference: 'sdf',
          responsibleDepartmentOrRole: 'sdf',
          locationOfRecords: 'sdf',
          itSystemUsed: 'sdf',
          appliedStandards: 'sdf',
        },
        quantityProductDetermination: {
          procedureDescription: 'asda',
          procedureDocumentName: 'sads',
          procedureReference: 'asdas',
          diagramReference: '345',
          responsibleDepartmentOrRole: 'sdf',
          locationOfRecords: 'dfg',
          itSystemUsed: '34534',
          appliedStandards: 'asd',
        },
        quantityMaterials: {
          procedureDescription: 'asdad',
          procedureDocumentName: 'sdf',
          procedureReference: 'werwe',
          diagramReference: 'sdf',
          responsibleDepartmentOrRole: 'bcvbcv',
          locationOfRecords: 'sdf',
          itSystemUsed: 'cvbcvb',
          appliedStandards: 'sdf',
        },
        gasFlowCalculation: {
          exist: false,
        },
        sourceStreamCategoryAppliedTiers: [
          {
            sourceStreamCategory: {
              sourceStream: '16285906590910.6068077459918291',
              emissionSources: ['16322182132590.5885074834095196'],
              emissionPoints: ['16285907821090.18383344328435758'],
              annualEmittedCO2Tonnes: 23.8,
              categoryType: 'MAJOR',
              emissionType: 'UNABATED',
              monitoringApproachType: 'CALCULATION',
            },
            measuredEmissions: {
              measurementDevicesOrMethods: ['16285908517990.09722032531195857'],
              samplingFrequency: 'CONTINUOUS',
              tier: 'TIER_3',
            },
            appliedStandard: {
              parameter: '1',
              appliedStandard: '2',
              deviationFromAppliedStandardExist: false,
              laboratoryName: 'g',
              laboratoryAccredited: false,
              laboratoryAccreditationEvidence: 'sfdf',
            },
          },
        ],
      } as any,
      MEASUREMENT: {
        type: 'MEASUREMENT',
        approachDescription: 'swwerew',
        emissionDetermination: {
          procedureDescription: 'fgh',
          procedureDocumentName: 'sdf',
          procedureReference: 'sdf',
          diagramReference: 'asdas',
          responsibleDepartmentOrRole: '345345',
          locationOfRecords: 'bbb',
          itSystemUsed: '345',
          appliedStandards: 'sdf',
        },
        referencePeriodDetermination: {
          procedureDescription: 'dsfsdf',
          procedureDocumentName: 'sdf',
          procedureReference: 'sdf',
          diagramReference: 'sdf',
          responsibleDepartmentOrRole: '345345',
          locationOfRecords: 'sdf',
          itSystemUsed: 'sdf',
          appliedStandards: 'sdf',
        },
        gasFlowCalculation: {
          exist: false,
        },
        biomassEmissions: {
          exist: false,
        },
        corroboratingCalculations: {
          procedureDescription: 'werer',
          procedureDocumentName: 'sdf',
          procedureReference: 'cvbcvb',
          diagramReference: 'sdf',
          responsibleDepartmentOrRole: '345345',
          locationOfRecords: 'sdf',
          itSystemUsed: '345',
          appliedStandards: 'sdf',
        },
        sourceStreamCategoryAppliedTiers: [
          {
            sourceStreamCategory: {
              sourceStream: '16285906590910.6068077459918291',
              emissionSources: ['16322182132590.5885074834095196'],
              emissionPoints: ['16285907821090.18383344328435758'],
              annualEmittedCO2Tonnes: 23.8,
              categoryType: 'MAJOR',
            },
            measuredEmissions: {
              measurementDevicesOrMethods: ['16285908517990.09722032531195857'],
              samplingFrequency: 'CONTINUOUS',
              isHighestRequiredTier: true,
              tier: 'TIER_1',
            },
            appliedStandard: {
              parameter: 'param1',
              appliedStandard: 'standard1',
              deviationFromAppliedStandardExist: true,
              deviationFromAppliedStandardDetails: 'deviation1',
              laboratoryName: 'lab1',
              laboratoryAccredited: false,
              laboratoryAccreditationEvidence: 'labEvidence',
            },
          },
        ],
      } as any,
    },
    uncertaintyAnalysis: {
      exist: true,
      attachments: ['743ba2e6-35c1-4181-b2fd-6a648361d691'],
    },
  },
  installationOperatorDetails: mockOnshore,
  permitSectionsCompleted: {
    monitoringApproachesPrepare: [true],
    sourceStreams: [true],
    emissionSources: [true],
    emissionPoints: [true],
    measurementDevicesOrMethods: [true],
    siteDiagrams: [true],
    environmentalPermitsAndLicences: [true],
    installationDescription: [true],
    regulatedActivities: [true],
    emissionSummaries: [true],
    estimatedAnnualEmissions: [true],
    monitoringReporting: [true],
    assignmentOfResponsibilities: [true],
    monitoringPlanAppropriateness: [true],
    managementProceduresExist: [true],
    confidentialityStatement: [true],
    monitoringApproaches: [true],
    abbreviations: [true],
    additionalDocuments: [true],
    qaDataFlowActivities: [true],
    dataFlowActivities: [true],
    reviewAndValidationOfData: [true],
    environmentalManagementSystem: [true],
    qaMeteringAndMeasuringEquipment: [true],
    assessAndControlRisk: [true],
    correctionsAndCorrectiveActions: [true],
    recordKeepingAndDocumentation: [true],
    controlOfOutsourcedActivities: [true],
    monitoringMethodologyPlans: [true],
    uncertaintyAnalysis: [true],
    N2O_Category: [true],
    N2O_Measured_Emissions: [true],
    N2O_Applied_Standard: [true],
    N2O_Description: [true],
    N2O_Emission: [true],
    N2O_Reference: [true],
    N2O_Operational: [true],
    N2O_Emissions: [true],
    N2O_Concentration: [true],
    N2O_Product: [true],
    N2O_Materials: [true],
    N2O_Gas: [true],
    MEASUREMENT_Description: [true],
    MEASUREMENT_Emission: [true],
    MEASUREMENT_Reference: [true],
    MEASUREMENT_Gasflow: [true],
    MEASUREMENT_Biomass: [true],
    MEASUREMENT_Corroborating: [true],
    MEASUREMENT_Category: [true],
    MEASUREMENT_Measured_Emissions: [true],
    MEASUREMENT_Applied_Standard: [true],
    FALLBACK_Category: [true],
    FALLBACK_Description: [true],
    FALLBACK_Uncertainty: [true],
    PFC_Description: [true],
    PFC_Types: [true],
    PFC_Efficiency: [true],
    PFC_Category: [true],
    PFC_Activity_Data: [true],
    PFC_Emission_Factor: [true],
    PFC_Tier2EmissionFactor: [true],
    INHERENT_CO2_Description: [true],
    TRANSFERRED_CO2_Installations: [true],
    TRANSFERRED_CO2_Accounting: [true],
    TRANSFERRED_CO2_Deductions: [true],
    TRANSFERRED_CO2_Leakage: [true],
    TRANSFERRED_CO2_Temperature: [true],
    TRANSFERRED_CO2_Transfer: [true],
    TRANSFERRED_CO2_Quantification: [true],
    TRANSFERRED_CO2_Description: [true],
  },
  permitAttachments: {
    '2c30c8bf-3d5e-474d-98a0-123a87eb60dd': 'cover.jpg',
    '60fe9548-ac65-492a-b057-60033b0fbbea': 'PublicationAgreement.pdf',
    '743ba2e6-35c1-4181-b2fd-6a648361d691': 'uncertainty.pdf',
  },
};
