FROM nginx:1.22
ENV XAUTH $HOME/.Xauthority

RUN rm /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/nginx.conf
COPY confs/nginx.conf /etc/nginx/nginx.conf
COPY confs/antora-site.conf /etc/nginx/conf.d/antora-site.conf
COPY uk-pmrv-docs-antora/build/site  /usr/share/nginx