import { RequestTaskDTO } from 'pmrv-api';

export const waitForRfiRdeTypes: Array<RequestTaskDTO['type']> = [
  'PERMIT_ISSUANCE_WAIT_FOR_RFI_RESPONSE',
  'PERMIT_ISSUANCE_WAIT_FOR_RDE_RESPONSE',
  'PERMIT_SURRENDER_WAIT_FOR_RFI_RESPONSE',
  'PERMIT_SURRENDER_WAIT_FOR_RDE_RESPONSE',
  'PERMIT_NOTIFICATION_WAIT_FOR_RFI_RESPONSE',
  'PERMIT_VARIATION_WAIT_FOR_RFI_RESPONSE',
  'PERMIT_VARIATION_WAIT_FOR_RDE_RESPONSE',
  // add here the rest of the workflow cases
];
