import { RequestTaskActionProcessDTO, RequestTaskDTO } from 'pmrv-api';

export const cancelActionMap: Partial<
  Record<RequestTaskDTO['type'], RequestTaskActionProcessDTO['requestTaskActionType']>
> = {
  PERMIT_NOTIFICATION_APPLICATION_SUBMIT: 'PERMIT_NOTIFICATION_CANCEL_APPLICATION',
  PERMIT_VARIATION_OPERATOR_APPLICATION_SUBMIT: 'PERMIT_VARIATION_CANCEL_APPLICATION',
  PERMIT_REVOCATION_APPLICATION_SUBMIT: 'PERMIT_REVOCATION_CANCEL_APPLICATION',
  PERMIT_SURRENDER_APPLICATION_SUBMIT: 'PERMIT_SURRENDER_CANCEL_APPLICATION',
};
