package uk.gov.pmrv.api.reporting.domain.nace;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum NaceCode {

    _13_PLANT_PROPAGATION("13 Plant propagation"),
    _15_MIXED_FARMING("15 Mixed farming"),
    _17_HUNTING_TRAPPING_AND_RELATED_SERVICE_ACTIVITIES("17 Hunting, trapping and related service activities"),
    _21_SILVICULTURE_AND_OTHER_FORESTRY_ACTIVITIES("21 Silviculture and other forestry activities"),
    _22_LOGGING("22 Logging"),
    _23_GATHERING_OF_WILD_GROWING_NON_WOOD_PRODUCTS("23 Gathering of wild growing non-wood products"),
    _24_SUPPORT_SERVICES_TO_FORESTRY("24 Support services to forestry"),
    _111_GROWING_OF_CEREAL_EXCEPT_RICE_LEGUMINOUS_CROPS_AND_OIL_SEEDS("111 Growing of cereals (except rice), leguminous crops and oil seeds"),
    _112_GROWING_OF_RICE("112 Growing of rice"),
    _113_GROWING_OF_VEGETABLES_AND_MELONS_ROOTS_AND_TUBERS("113 Growing of vegetables and melons, roots and tubers"),
    _114_GROWING_OF_SUGAR_CANE("114 Growing of sugar cane"),
    _115_GROWING_OF_TOBACCO("115 Growing of tobacco"),
    _116_GROWING_OF_FIBRE_CROPS("116 Growing of fibre crops"),
    _119_GROWING_OF_OTHER_NON_PERENNIAL_CROPS("119 Growing of other non-perennial crops"),
    _121_GROWING_OF_GRAPES("121 Growing of grapes"),
    _122_GROWING_OF_TROPICAL_AND_SUBTROPICAL_FRUITS("122 Growing of tropical and subtropical fruits"),
    _123_GROWING_OF_CITRUS_FRUITS("123 Growing of citrus fruits"),
    _124_GROWING_OF_POME_FRUITS_AND_STONE_FRUITS("124 Growing of pome fruits and stone fruits"),
    _125_GROWING_OF_OTHER_TREE_AND_BUSH_FRUITS_AND_NUTS("125 Growing of other tree and bush fruits and nuts"),
    _126_GROWING_OF_OLEAGINOUS_FRUITS("126 Growing of oleaginous fruits"),
    _127_GROWING_OF_BEVERAGE_CROPS("127 Growing of beverage crops"),
    _128_GROWING_OF_SPICES_AROMATIC_DRUG_AND_PHARMACEUTICAL_CROPS("128 Growing of spices, aromatic, drug and pharmaceutical crops"),
    _129_GROWING_OF_OTHER_PERENNIAL_CROPS("129 Growing of other perennial crops"),
    _141_RAISING_OF_DAIRY_CATTLE("141 Raising of dairy cattle"),
    _142_RAISING_OF_OTHER_CATTLE_AND_BUFFALOES("142 Raising of other cattle and buffaloes"),
    _143_RAISING_OF_HORSES_AND_OTHER_EQUINES("143 Raising of horses and other equines"),
    _144_RAISING_OF_CAMELS_AND_CAMELIDS("144 Raising of camels and camelids"),
    _145_RAISING_OF_SHEEP_AND_GOATS("145 Raising of sheep and goats"),
    _146_RAISING_OF_SWINE_PIGS("146 Raising of swine/pigs"),
    _147_RAISING_OF_POULTRY("147 Raising of poultry"),
    _149_RAISING_OF_OTHER_ANIMALS("149 Raising of other animals"),
    _161_SUPPORT_ACTIVITIES_FOR_CROP_PRODUCTION("161 Support activities for crop production"),
    _162_SUPPORT_ACTIVITIES_FOR_ANIMAL_PRODUCTION("162 Support activities for animal production"),
    _163_POST_HARVEST_CROP_ACTIVITIES("163 Post-harvest crop activities"),
    _164_SEED_PROCESSING_FOR_PROPAGATION("164 Seed processing for propagation"),
    _311_MARINE_FISHING("311 Marine fishing"),
    _312_FRESHWATER_FISHING("312 Freshwater fishing"),
    _321_MARINE_AQUACULTURE("321 Marine aquaculture"),
    _322_FRESHWATER_AQUACULTURE("322 Freshwater aquaculture"),
    _51_MINING_OF_HARD_COAL("51 Mining of hard coal"),
    _52_MINING_OF_LIGNITE("52 Mining of lignite"),
    _61_EXTRACTION_OF_CRUDE_PETROLEUM("61 Extraction of crude petroleum"),
    _62_EXTRACTION_OF_NATURAL_GAS("62 Extraction of natural gas"),
    _71_MINING_OF_IRON_ORES("71 Mining of iron ores"),
    _91_SUPPORT_ACTIVITIES_FOR_PETROLEUM_AND_NATURAL_GAS_EXTRACTION("91 Support activities for petroleum and natural gas extraction"),
    _99_SUPPORT_ACTIVITIES_FOR_OTHER_MINING_AND_QUARRYING("99 Support activities for other mining and quarrying"),
    _102_PROCESSING_AND_PRESERVING_OF_FISH_CRUSTACEANS_AND_MOLLUSCS("102 Processing and preserving of fish, crustaceans and molluscs"),
    _721_MINING_OF_URANIUM_AND_THORIUM_ORES("721 Mining of uranium and thorium ores"),
    _729_MINING_OF_OTHER_NON_FERROUS_METAL_ORES("729 Mining of other non-ferrous metal ores"),
    _811_QUARRYING_OF_ORNAMENTAL_AND_BUILDING_STONE_LIMESTONE_GYPSUM_CHALK_AND_SLATE("811 Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate"),
    _812_OPERATION_OF_GRAVEL_AND_SAND_PITS_MINING_OF_CLAYS_AND_KAOLIN("812 Operation of gravel and sand pits; mining of clays and kaolin"),
    _891_MINING_OF_CHEMICAL_AND_FERTILISER_MINERALS("891 Mining of chemical and fertiliser minerals"),
    _892_EXTRACTION_OF_PEAT("892 Extraction of peat"),
    _893_EXTRACTION_OF_SALT("893 Extraction of salt"),
    _899_OTHER_MINING_AND_QUARRYING_N_E_C("899 Other mining and quarrying n.e.c."),
    _120_MANUFACTURE_OF_TOBACCO_PRODUCTS("120 Manufacture of tobacco products"),
    _131_PREPARATION_AND_SPINNING_OF_TEXTILE_FIBRES("131 Preparation and spinning of textile fibres"),
    _132_WEAVING_OF_TEXTILES("132 Weaving of textiles"),
    _133_FINISHING_OF_TEXTILES("133 Finishing of textiles"),
    _142_MANUFACTURE_OF_ARTICLES_OF_FUR("142 Manufacture of articles of fur"),
    _152_MANUFACTURE_OF_FOOTWEAR("152 Manufacture of footwear"),
    _161_SAWMILLING_AND_PLANING_OF_WOOD("161 Sawmilling and planing of wood"),
    _182_REPRODUCTION_OF_RECORDED_MEDIA("182 Reproduction of recorded media"),
    _191_MANUFACTURE_OF_COKE_OVEN_PRODUCTS("191 Manufacture of coke oven products"),
    _192_MANUFACTURE_OF_REFINED_PETROLEUM_PRODUCTS("192 Manufacture of refined petroleum products"),
    _202_MANUFACTURE_OF_PESTICIDES_AND_OTHER_AGROCHEMICAL_PRODUCTS("202 Manufacture of pesticides and other agrochemical products"),
    _203_MANUFACTURE_OF_PAINTS_VARNISHES_AND_SIMILAR_COATINGS_PRINTING_INK_AND_MASTICS("203 Manufacture of paints, varnishes and similar coatings, printing ink and mastics"),
    _206_MANUFACTURE_OF_MAN_MADE_FIBRES("206 Manufacture of man-made fibres"),
    _211_MANUFACTURE_OF_BASIC_PHARMACEUTICAL_PRODUCTS("211 Manufacture of basic pharmaceutical products"),
    _212_MANUFACTURE_OF_PHARMACEUTICAL_PREPARATIONS("212 Manufacture of pharmaceutical preparations"),
    _232_MANUFACTURE_OF_REFRACTORY_PRODUCTS("232 Manufacture of refractory products"),
    _237_CUTTING_SHAPING_AND_FINISHING_OF_STONE("237 Cutting, shaping and finishing of stone"),
    _241_MANUFACTURE_OF_BASIC_IRON_AND_STEEL_AND_OF_FERRO_ALLOYS("241 Manufacture of basic iron and steel and of ferro-alloys"),
    _242_MANUFACTURE_OF_TUBES_PIPES_HOLLOW_PROFILES_AND_RELATED_FITTINGS_OF_STEEL("242 Manufacture of tubes, pipes, hollow profiles and related fittings, of steel"),
    _253_MANUFACTURE_OF_STEAM_GENERATORS_EXCEPT_CENTRAL_HEATING_HOT_WATER_BOILERS("253 Manufacture of steam generators, except central heating hot water boilers"),
    _254_MANUFACTURE_OF_WEAPONS_AND_AMMUNITION("254Manufacture of weapons and ammunition"),
    _255_FORGING_PRESSING_STAMPING_AND_ROLL_FORMING_OF_METAL_POWDER_METALLURGY("255 Forging, pressing, stamping and roll-forming of metal; powder metallurgy"),
    _262_MANUFACTURE_OF_COMPUTERS_AND_PERIPHERAL_EQUIPMENT("262 Manufacture of computers and peripheral equipment"),
    _263_MANUFACTURE_OF_COMMUNICATION_EQUIPMENT("263 Manufacture of communication equipment"),
    _264_MANUFACTURE_OF_CONSUMER_ELECTRONICS("264 Manufacture of consumer electronics"),
    _266_MANUFACTURE_OF_IRRADIATION_ELECTROMEDICAL_AND_ELECTROTHERAPEUTIC_EQUIPMENT("266 Manufacture of irradiation, electromedical and electrotherapeutic equipment"),
    _267_MANUFACTURE_OF_OPTICAL_INSTRUMENTS_AND_PHOTOGRAPHIC_EQUIPMENT("267 Manufacture of optical instruments and photographic equipment"),
    _268_MANUFACTURE_OF_MAGNETIC_AND_OPTICAL_MEDIA("268 Manufacture of magnetic and optical media"),
    _272_MANUFACTURE_OF_BATTERIES_AND_ACCUMULATORS("272 Manufacture of batteries and accumulators"),
    _274_MANUFACTURE_OF_ELECTRIC_LIGHTING_EQUIPMENT("274 Manufacture of electric lighting equipment"),
    _283_MANUFACTURE_OF_AGRICULTURAL_AND_FORESTRY_MACHINERY("283 Manufacture of agricultural and forestry machinery"),
    _1011_PROCESSING_AND_PRESERVING_OF_MEAT("1011 Processing and preserving of meat"),
    _1012_PROCESSING_AND_PRESERVING_OF_POULTRY_MEAT("1012 Processing and preserving of poultry meat"),
    _1013_PRODUCTION_OF_MEAT_AND_POULTRY_MEAT_PRODUCTS("1013 Production of meat and poultry meat products"),
    _1031_PROCESSING_AND_PRESERVING_OF_POTATOES("1031 Processing and preserving of potatoes"),
    _1032_MANUFACTURE_OF_FRUIT_AND_VEGETABLE_JUICE("1032 Manufacture of fruit and vegetable juice"),
    _1039_OTHER_PROCESSING_AND_PRESERVING_OF_FRUIT_AND_VEGETABLES("1039 Other processing and preserving of fruit and vegetables"),
    _1041_MANUFACTURE_OF_OILS_AND_FATS("1041 Manufacture of oils and fats"),
    _1042_MANUFACTURE_OF_MARGARINE_AND_SIMILAR_EDIBLE_FATS("1042 Manufacture of margarine and similar edible fats"),
    _1051_OPERATION_OF_DAIRIES_AND_CHEESE_MAKING("1051 Operation of dairies and cheese making"),
    _1052_MANUFACTURE_OF_ICE_CREAM("1052 Manufacture of ice cream"),
    _1061_MANUFACTURE_OF_GRAIN_MILL_PRODUCTS("1061 Manufacture of grain mill products"),
    _1062_MANUFACTURE_OF_STARCHES_AND_STARCH_PRODUCTS("1062 Manufacture of starches and starch products"),
    _1071_MANUFACTURE_OF_BREAD_MANUFACTURE_OF_FRESH_PASTRY_GOODS_AND_CAKES("1071 Manufacture of bread; manufacture of fresh pastry goods and cakes"),
    _1072_MANUFACTURE_OF_RUSKS_AND_BISCUITS_MANUFACTURE_OF_PRESERVED_PASTRY_GOODS_AND_CAKES("1072 Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes"),
    _1073_MANUFACTURE_OF_MACARONI_NOODLES_COUSCOUS_AND_SIMILAR_FARINACEOUS_PRODUCTS("1073 Manufacture of macaroni, noodles, couscous and similar farinaceous products"),
    _1081_MANUFACTURE_OF_SUGAR("1081 Manufacture of sugar"),
    _1082_MANUFACTURE_OF_COCOA_CHOCOLATE_AND_SUGAR_CONFECTIONERY("1082 Manufacture of cocoa, chocolate and sugar confectionery"),
    _1083_PROCESSING_OF_TEA_AND_COFFEE("1083 Processing of tea and coffee"),
    _1084_MANUFACTURE_OF_CONDIMENTS_AND_SEASONINGS("1084 Manufacture of condiments and seasonings"),
    _1085_MANUFACTURE_OF_PREPARED_MEALS_AND_DISHES("1085 Manufacture of prepared meals and dishes"),
    _1086_MANUFACTURE_OF_HOMOGENISED_FOOD_PREPARATIONS_AND_DIETETIC_FOOD("1086 Manufacture of homogenised food preparations and dietetic food"),
    _1089_MANUFACTURE_OF_OTHER_FOOD_PRODUCTS_N_E_C("1089 Manufacture of other food products n.e.c."),
    _1091_MANUFACTURE_OF_PREPARED_FEEDS_FOR_FARM_ANIMALS("1091 Manufacture of prepared feeds for farm animals"),
    _1092_MANUFACTURE_OF_PREPARED_PET_FOODS("1092 Manufacture of prepared pet foods"),
    _1101_DISTILLING_RECTIFYING_AND_BLENDING_OF_SPIRITS("1101 Distilling, rectifying and blending of spirits"),
    _1102_MANUFACTURE_OF_WINE_FROM_GRAPE("1102 Manufacture of wine from grape"),
    _1103_MANUFACTURE_OF_CIDER_AND_OTHER_FRUIT_WINES("1103 Manufacture of cider and other fruit wines"),
    _1104_MANUFACTURE_OF_OTHER_NON_DISTILLED_FERMENTED_BEVERAGES("1104 Manufacture of other non-distilled fermented beverages"),
    _1105_MANUFACTURE_OF_BEER("1105 Manufacture of beer"),
    _1106_MANUFACTURE_OF_MALT("1106 Manufacture of malt"),
    _1107_MANUFACTURE_OF_SOFT_DRINKS_PRODUCTION_OF_MINERAL_WATERS_AND_OTHER_BOTTLED_WATERS("1107 Manufacture of soft drinks; production of mineral waters and other bottled waters"),
    _1391_MANUFACTURE_OF_KNITTED_AND_CROCHETED_FABRICS("1391 Manufacture of knitted and crocheted fabrics"),
    _1392_MANUFACTURE_OF_MADE_UP_TEXTILE_ARTICLES_EXCEPT_APPAREL("1392 Manufacture of made-up textile articles, except apparel"),
    _1393_MANUFACTURE_OF_CARPETS_AND_RUGS("Manufacture of carpets and rugs"),
    _1394_MANUFACTURE_OF_CORDAGE_ROPE_TWINE_AND_NETTING("Manufacture of cordage, rope, twine and netting"),
    _1395_MANUFACTURE_OF_NON_WOVENS_AND_ARTICLES_MADE_FROM_NON_WOVENS_EXCEPT_APPAREL("Manufacture of non-wovens and articles made from non-wovens, except apparel"),
    _1396_MANUFACTURE_OF_OTHER_TECHNICAL_AND_INDUSTRIAL_TEXTILES("Manufacture of other technical and industrial textiles"),
    _1399_MANUFACTURE_OF_OTHER_TEXTILES_N_E_C_("1399 Manufacture of other textiles n.e.c."),
    _1411_MANUFACTURE_OF_LEATHER_CLOTHES("1411 Manufacture of leather clothes"),
    _1412_MANUFACTURE_OF_WORKWEAR("1412 Manufacture of workwear"),
    _1413_MANUFACTURE_OF_OTHER_OUTERWEAR("1413 Manufacture of other outerwear"),
    _1414_MANUFACTURE_OF_UNDERWEAR("1414 Manufacture of underwear"),
    _1419_MANUFACTURE_OF_OTHER_WEARING_APPAREL_AND_ACCESSORIES("1419 Manufacture of other wearing apparel and accessories"),
    _1431_MANUFACTURE_OF_KNITTED_AND_CROCHETED_HOSIERY("1431 Manufacture of knitted and crocheted hosiery"),
    _1439_MANUFACTURE_OF_OTHER_KNITTED_AND_CROCHETED_APPAREL("1439 Manufacture of other knitted and crocheted apparel"),
    _1511_TANNING_AND_DRESSING_OF_LEATHER_DRESSING_AND_DYEING_OF_FUR("1511 Tanning and dressing of leather; dressing and dyeing of fur"),
    _1512_MANUFACTURE_OF_LUGGAGE_HANDBAGS_AND_THE_LIKE_SADDLERY_AND_HARNESS("1512 Manufacture of luggage, handbags and the like, saddlery and harness"),
    _1621_MANUFACTURE_OF_VENEER_SHEETS_AND_WOOD_BASED_PANELS("1621 Manufacture of veneer sheets and wood-based panels"),
    _1622_MANUFACTURE_OF_ASSEMBLED_PARQUET_FLOORS("1622 Manufacture of assembled parquet floors"),
    _1623_MANUFACTURE_OF_OTHER_BUILDERS_CARPENTRY_AND_JOINERY("1623 Manufacture of other builders' carpentry and joinery"),
    _1624_MANUFACTURE_OF_WOODEN_CONTAINERS("1624 Manufacture of wooden containers"),
    _1629_MANUFACTURE_OF_OTHER_PRODUCTS_OF_WOOD_MANUFACTURE_OF_ARTICLES_OF_CORK_STRAW_AND_PLAINTING_MATERIALS("1629 Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials"),
    _1711_MANUFACTURE_OF_PULP("1711 Manufacture of pulp"),
    _1712_MANUFACTURE_OF_PAPER_AND_PAPERBOARD("1712 Manufacture of paper and paperboard"),
    _1721_MANUFACTURE_OF_CORRUGATED_PAPER_AND_PAPERBOARD_AND_OF_CONTAINERS_OF_PAPER_AND_PAPERBOA("1721 Manufacture of corrugated paper and paperboard and of containers of paper and paperboard"),
    _1722_MANUFACTURE_OF_HOUSEHOLD_AND_SANITARY_GOODS_AND_OF_TOILET_REQUISITES("1722 Manufacture of household and sanitary goods and of toilet requisites"),
    _1723_MANUFACTURE_OF_PAPER_STATIONERY("1723 Manufacture of paper stationery"),
    _1724_MANUFACTURE_OF_WALLPAPER("1724 Manufacture of wallpaper"),
    _1729_MANUFACTURE_OF_OTHER_ARTICLES_OF_PAPER_AND_PAPERBOARD("1729 Manufacture of other articles of paper and paperboard"),
    _1811_PRINTING_OF_NEWSPAPERS("1811 Printing of newspapers"),
    _1812_OTHER_PRINTING("1812 Other printing"),
    _1813_PRE_PRESS_AND_PRE_MEDIA_SERVICES("1813 Pre-press and pre-media services"),
    _1814_BINDING_AND_RELATED_SERVICES("1814 Binding and related services"),
    _2011_MANUFACTURE_OF_INDUSTRIAL_GASES("2011 Manufacture of industrial gases"),
    _2012_MANUFACTURE_OF_DYES_AND_PIGMENTS("2012 Manufacture of dyes and pigments"),
    _2013_MANUFACTURE_OF_OTHER_INORGANIC_BASIC_CHEMICALS("2013 Manufacture of other inorganic basic chemicals"),
    _2014_MANUFACTURE_OF_OTHER_ORGANIC_BASIC_CHEMICALS("2014 Manufacture of other organic basic chemicals"),
    _2015_MANUFACTURE_OF_FERTILISERS_AND_NITROGEN_COMPOUNDS("2015 Manufacture of fertilisers and nitrogen compounds"),
    _2016_MANUFACTURE_OF_PLASTICS_IN_PRIMARY_FORMS("2016 Manufacture of plastics in primary forms"),
    _2017_MANUFACTURE_OF_SYNTHETIC_RUBBER_IN_PRIMARY_FORMS("2017 Manufacture of synthetic rubber in primary forms"),
    _2041_MANUFACTURE_OF_SOAP_AND_DETERGENTS_CLEANING_AND_POLISHING_PREPARATIONS("2041 Manufacture of soap and detergents, cleaning and polishing preparations"),
    _2042_MANUFACTURE_OF_PERFUMES_AND_TOILET_PREPARATIONS("2042 Manufacture of perfumes and toilet preparations"),
    _2051_MANUFACTURE_OF_EXPLOSIVES("2051 Manufacture of explosives"),
    _2052_MANUFACTURE_OF_GLUES("2052 Manufacture of glues"),
    _2053_MANUFACTURE_OF_ESSENTIAL_OILS("2053 Manufacture of essential oils"),
    _2059_MANUFACTURE_OF_OTHER_CHEMICAL_PRODUCTS_N_E_C_("2059 Manufacture of other chemical products n.e.c."),
    _2211_MANUFACTURE_OF_RUBBER_TYRES_AND_TUBES_RETREADING_AND_REBUILDING_OF_RUBBER_TYRES("2211 Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres"),
    _2219_MANUFACTURE_OF_OTHER_RUBBER_PRODUCTS("2219 Manufacture of other rubber products"),
    _2221_MANUFACTURE_OF_PLASTIC_PLATES_SHEETS_TUBES_AND_PROFILES("2221 Manufacture of plastic plates, sheets, tubes and profiles"),
    _2222_MANUFACTURE_OF_PLASTIC_PACKING_GOODS("2222 Manufacture of plastic packing goods"),
    _2223_MANUFACTURE_OF_BUILDERS_WARE_OF_PLASTIC("2223 Manufacture of builders' ware of plastic"),
    _2229_MANUFACTURE_OF_OTHER_PLASTIC_PRODUCTS("2229 Manufacture of other plastic products"),
    _2311_MANUFACTURE_OF_FLAT_GLASS("2311 Manufacture of flat glass"),
    _2312_SHAPING_AND_PROCESSING_OF_FLAT_GLASS("2312 Shaping and processing of flat glass"),
    _2313_MANUFACTURE_OF_HOLLOW_GLASS("2313 Manufacture of hollow glass"),
    _2314_MANUFACTURE_OF_GLASS_FIBRES("2314 Manufacture of glass fibres"),
    _2319_MANUFACTURE_AND_PROCESSING_OF_OTHER_GLASS_INCLUDING_TECHNICAL_GLASSWARE("2319 Manufacture and processing of other glass, including technical glassware"),
    _2331_MANUFACTURE_OF_CERAMIC_TILES_AND_FLAGS("2331 Manufacture of ceramic tiles and flags"),
    _2332_MANUFACTURE_OF_BRICKS_TILES_AND_CONSTRUCTION_PRODUCTS_IN_BAKED_CLAY("2332 Manufacture of bricks, tiles and construction products, in baked clay"),
    _2341_MANUFACTURE_OF_CERAMIC_HOUSEHOLD_AND_ORNAMENTAL_ARTICLES("2341 Manufacture of ceramic household and ornamental articles"),
    _2342_MANUFACTURE_OF_CERAMIC_SANITARY_FIXTURES("2342 Manufacture of ceramic sanitary fixtures"),
    _2343_MANUFACTURE_OF_CERAMIC_INSULATORS_AND_INSULATING_FITTINGS("2343 Manufacture of ceramic insulators and insulating fittings"),
    _2344_MANUFACTURE_OF_OTHER_TECHNICAL_CERAMIC_PRODUCTS("2344 Manufacture of other technical ceramic products"),
    _2349_MANUFACTURE_OF_OTHER_CERAMIC_PRODUCTS("2349 Manufacture of other ceramic products"),
    _2351_MANUFACTURE_OF_CEMENT("2351 Manufacture of cement"),
    _2352_MANUFACTURE_OF_LIME_AND_PLASTER("2352 Manufacture of lime and plaster"),
    _2361_MANUFACTURE_OF_CONCRETE_PRODUCTS_FOR_CONSTRUCTION_PURPOSES("2361 Manufacture of concrete products for construction purposes"),
    _2362_MANUFACTURE_OF_PLASTER_PRODUCTS_FOR_CONSTRUCTION_PURPOSES("2362 Manufacture of plaster products for construction purposes"),
    _2363_MANUFACTURE_OF_READY_MIXED_CONCRETE("2363 Manufacture of ready-mixed concrete"),
    _2464_MANUFACTURE_OF_MORTARS("2464 Manufacture of mortars"),
    _2465_MANUFACTURE_OF_FIBRE_CEMENT("2465 Manufacture of fibre cement"),
    _2469_MANUFACTURE_OF_OTHER_ARTICLES_OF_CONCRETE_PLASTER_AND_CEMENT("2469 Manufacture of other articles of concrete, plaster and cement"),
    _2391_PRODUCTION_OF_ABRASIVE_PRODUCTS("2391 Production of abrasive products"),
    _2399_MANUFACTURE_OF_OTHER_NON_METALLIC_MINERAL_PRODUCTS_N_E_C_("2399 Manufacture of other non-metallic mineral products n.e.c."),
    _2431_COLD_DRAWING_OF_BARS("2431 Cold drawing of bars"),
    _2432_COLD_ROLLING_OF_NARROW_STRIP("2432 Cold rolling of narrow strip"),
    _2433_COLD_FORMING_OR_FOLDING("2433 Cold forming or folding"),
    _2434_COLD_DRAWING_OF_WIRE("2434 Cold drawing of wire"),
    _2441_PRECIOUS_METALS_PRODUCTION("2441 Precious metals production"),
    _2442_ALUMINIUM_PRODUCTION("2442 Aluminium production"),
    _2443_LEAD_ZINC_AND_TIN_PRODUCTION("2443 Lead, zinc and tin production"),
    _2444_COPPER_PRODUCTION("2444 Copper production"),
    _2445_OTHER_NON_FERROUS_METAL_PRODUCTION("2445 Other non-ferrous metal production"),
    _2446_PROCESSING_OF_NUCLEAR_FUEL("2446 Processing of nuclear fuel"),
    _2451_CASTING_OF_IRON("2451 Casting of iron"),
    _2452_CASTING_OF_STEEL("2452 Casting of steel"),
    _2453_CASTING_OF_LIGHT_METALS("2453 Casting of light metals"),
    _2454_CASTING_OF_OTHER_NON_FERROUS_METALS("2454 Casting of other non-ferrous metals"),
    _2511_MANUFACTURE_OF_METAL_STRUCTURES_AND_PARTS_OF_STRUCTURES("2511 Manufacture of metal structures and parts of structures"),
    _2512_MANUFACTURE_OF_DOORS_AND_WINDOWS_OF_METAL("2512 Manufacture of doors and windows of metal"),
    _2521_MANUFACTURE_OF_CENTRAL_HEATING_RADIATORS_AND_BOILERS("2521 Manufacture of central heating radiators and boilers"),
    _2529_MANUFACTURE_OF_OTHER_TANKS_RESERVOIRS_AND_CONTAINERS_OF_METAL("2529 Manufacture of other tanks, reservoirs and containers of metal"),
    _2561_TREATMENT_AND_COATING_OF_METALS("2561 Treatment and coating of metals"),
    _2562_MACHINING("2562 Machining"),
    _2571_MANUFACTURE_OF_CUTLERY("2571 Manufacture of cutlery"),
    _2572_MANUFACTURE_OF_LOCKS_AND_HINGES("2572 Manufacture of locks and hinges"),
    _2573_MANUFACTURE_OF_TOOLS("2573 Manufacture of tools"),
    _2591_MANUFACTURE_OF_STEEL_DRUMS_AND_SIMILAR_CONTAINERS("2591 Manufacture of steel drums and similar containers"),
    _2592_MANUFACTURE_OF_LIGHT_METAL_PACKAGING("2592 Manufacture of light metal packaging"),
    _2593_MANUFACTURE_OF_WIRE_PRODUCTS_CHAIN_AND_SPRINGS("2593 Manufacture of wire products, chain and springs"),
    _2594_MANUFACTURE_OF_FASTENERS_AND_SCREW_MACHINE_PRODUCTS("2594 Manufacture of fasteners and screw machine products"),
    _2599_MANUFACTURE_OF_OTHER_FABRICATED_METAL_PRODUCTS_N_E_C_("2599 Manufacture of other fabricated metal products n.e.c."),
    _2611_MANUFACTURE_OF_ELECTRONIC_COMPONENTS("2611 Manufacture of electronic components"),
    _2612_MANUFACTURE_OF_LOADED_ELECTRONIC_BOARDS("2612 Manufacture of loaded electronic boards"),
    _2651_MANUFACTURE_OF_INSTRUMENTS_AND_APPLIANCES_FOR_MEASURING_TESTING_AND_NAVIGATION("2651 Manufacture of instruments and appliances for measuring, testing and navigation"),
    _2652_MANUFACTURE_OF_WATCHES_AND_CLOCKS("2652 Manufacture of watches and clocks"),
    _2711_MANUFACTURE_OF_ELECTRIC_MOTORS_GENERATORS_AND_TRANSFORMERS("2711 Manufacture of electric motors, generators and transformers"),
    _2712_MANUFACTURE_OF_ELECTRICITY_DISTRIBUTION_AND_CONTROL_APPARATUS("2712 Manufacture of electricity distribution and control apparatus"),
    _2731_MANUFACTURE_OF_FIBRE_OPTIC_CABLES("2731 Manufacture of fibre optic cables"),
    _2732_MANUFACTURE_OF_OTHER_ELECTRONIC_AND_ELECTRIC_WIRES_AND_CABLES("2732 Manufacture of other electronic and electric wires and cables"),
    _2733_MANUFACTURE_OF_WIRING_DEVICES("2733 Manufacture of wiring devices"),
    _2751_MANUFACTURE_OF_ELECTRIC_DOMESTIC_APPLIANCES("2751 Manufacture of electric domestic appliances"),
    _2752_MANUFACTURE_OF_NON_ELECTRIC_DOMESTIC_APPLIANCES("2752 Manufacture of non-electric domestic appliances"),
    _279_MANUFACTURE_OF_OTHER_ELECTRICAL_EQUIPMENT("279 Manufacture of other electrical equipment"),
    _2811_MANUFACTURE_OF_ENGINES_AND_TURBINES_EXCEPT_AIRCRAFT_VEHICLE_AND_CYCLE_ENGINES("2811 Manufacture of engines and turbines, except aircraft, vehicle and cycle engines"),
    _2812_MANUFACTURE_OF_FLUID_POWER_EQUIPMENT("2812 Manufacture of fluid power equipment"),
    _2813_MANUFACTURE_OF_OTHER_PUMPS_AND_COMPRESSORS("2813 Manufacture of other pumps and compressors"),
    _2814_MANUFACTURE_OF_OTHER_TAPS_AND_VALVES("2814 Manufacture of other taps and valves"),
    _2815_MANUFACTURE_OF_BEARINGS_GEARS_GEARING_AND_DRIVING_ELEMENTS("2815 Manufacture of bearings, gears, gearing and driving elements"),
    _2821_MANUFACTURE_OF_OVENS_FURNACES_AND_FURNACE_BURNERS("2821 Manufacture of ovens, furnaces and furnace burners"),
    _2822_MANUFACTURE_OF_LIFTING_AND_HANDLING_EQUIPMENT("2822 Manufacture of lifting and handling equipment"),
    _2823_MANUFACTURE_OF_OFFICE_MACHINERY_AND_EQUIPMENT_EXCEPT_COMPUTERS_AND_PERIPHERAL_EQUIPMENT("2823 Manufacture of office machinery and equipment (except computers and peripheral equipment)"),
    _2824_MANUFACTURE_OF_POWER_DRIVEN_HAND_TOOLS("2824 Manufacture of power-driven hand tools"),
    _2825_MANUFACTURE_OF_NON_COOLING_AND_VENTILATION_EQUIPMENT("2825 Manufacture of non-domestic cooling and ventilation equipment"),
    _2829_MANUFACTURE_OF_OTHER_GENERAL_PURPOSE_MACHINERY_N_E_C_("2829 Manufacture of other general-purpose machinery n.e.c."),
    _2841_MANUFACTURE_OF_METAL_FORMING_MACHINERY("2841 Manufacture of metal forming machinery"),
    _2849_MANUFACTURE_OF_OTHER_MACHINE_TOOLS("2849 Manufacture of other machine tools"),
    _2891_MANUFACTURE_OF_MACHINERY_FOR_METALLURGY("2891 Manufacture of machinery for metallurgy"),
    _2892_MANUFACTURE_OF_MACHINERY_FOR_MINING_QUARRYING_AND_CONSTRUCTION("2892 Manufacture of machinery for mining, quarrying and construction"),
    _2893_MANUFACTURE_OF_MACHINERY_FOR_FOOD_BEVERAGE_AND_TOBACCO_PROCESSING("2893 Manufacture of machinery for food, beverage and tobacco processing"),
    _2894_MANUFACTURE_OF_MACHINERY_FOR_TEXTILE_APPAREL_AND_LEATHER_PRODUCTION("2894 Manufacture of machinery for textile, apparel and leather production"),
    _2895_MANUFACTURE_OF_MACHINERY_FOR_PAPER_AND_PAPERBOARD_PRODUCTION("2895 Manufacture of machinery for paper and paperboard production"),
    _2896_MANUFACTURE_OF_PLASTIC_AND_RUBBER_MACHINERY("2896 Manufacture of plastic and rubber machinery"),
    _2899_MANUFACTURE_OF_OTHER_SPECIAL_PURPOSE_MACHINERY_N_E_C_("2899 Manufacture of other special-purpose machinery n.e.c."),
    _291_MANUFACTURE_OF_MOTOR_VEHICLES("291 Manufacture of motor vehicles"),
    _292_MANUFACTURE_OF_BODIES_COACHWORK_FOR_MOTOR_VEHICLES_MANUFACTURE_TRAILERS_AND_SEMI_TRAILERS("292 Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers"),
    _2931_MANUFACTURE_OF_ELECTRICAL_EQUIPMENT_FOR_MOTOR_VEHICLES("2931 Manufacture of electrical and electronic equipment for motor vehicles"),
    _2932_MANUFACTURE_OF_OTHER_PARTS_AND_ACCESSORIES_FOR_MOTOR_VEHICLES("2932 Manufacture of other parts and accessories for motor vehicles"),
    _3011_BUILDING_OF_SHIPS_AND_FLOATING_STRUCTURES("3011 Building of ships and floating structures"),
    _3012_BUILDING_OF_PLEASURE_AND_SPORTING_BOATS("3012 Building of pleasure and sporting boats"),
    _302_MANUFACTURE_OF_RAILWAY_LOCOMOTIVES_AND_ROLLING_STOCK("302 Manufacture of railway locomotives and rolling stock"),
    _303_MANUFACTURE_OF_AIR_AND_SPACECRAFT_AND_RELATED_MACHINERY("303 Manufacture of air and spacecraft and related machinery"),
    _304_MANUFACTURE_OF_MILITARY_FIGHTING_VEHICLES("304 Manufacture of military fighting vehicles"),
    _3091_MANUFACTURE_OF_MOTORCYCLES("3091 Manufacture of motorcycles"),
    _3092_MANUFACTURE_OF_BICYCLES_AND_INVALID_CARRIAGES("3092 Manufacture of bicycles and invalid carriages"),
    _3099_MANUFACTURE_OF_OTHER_TRANSPORT_EQUIPMENT_N_E_C_("3099 Manufacture of other transport equipment n.e.c."),
    _3101_MANUFACTURE_OF_OFFICE_AND_SHOP_FURNITURE("3101 Manufacture of office and shop furniture"),
    _3102_MANUFACTURE_OF_KITCHEN_FURNITURE("3102 Manufacture of kitchen furniture"),
    _3103_MANUFACTURE_OF_MATTRESSES("3103 Manufacture of mattresses"),
    _3109_MANUFACTURE_OF_OTHER_FURNITURE("3109 Manufacture of other furniture"),
    _3211_STRIKING_OF_COINS("3211 Striking of coins"),
    _3212_MANUFACTURE_OF_JEWELLERY_AND_RELATED_ARTICLES("3212 Manufacture of jewellery and related articles"),
    _3213_MANUFACTURE_OF_IMITATION_JEWELLERY_AND_RELATED_ACTIVITIES("3213 Manufacture of imitation jewellery and related articles"),
    _322_MANUFACTURE_OF_MUSICAL_INSTRUMENTS("322 Manufacture of musical instruments"),
    _323_MANUFACTURE_OF_SPORTS_GOODS("323 Manufacture of sports goods"),
    _324_MANUFACTURE_OF_GAMES_AND_TOYS("324 Manufacture of games and toys"),
    _325_MANUFACTURE_OF_MEDICAL_AND_DENTAL_INSTRUMENTS_AND_SUPPLIES("325 Manufacture of medical and dental instruments and supplies"),
    _3291_MANUFACTURE_OF_BROOMS_AND_BRUSHES("3291 Manufacture of brooms and brushes"),
    _3299_OTHER_MANUFACTURING_N_E_C_("3299 Other manufacturing n.e.c."),
    _3311_REPAIR_OF_FABRICATED_METAL_PRODUCTS("3311 Repair of fabricated metal products"),
    _3312_REPAIR_OF_MACHINERY("3312 Repair of machinery"),
    _3313_REPAIR_OF_ELECTRONIC_AND_OPTICAL_EQUIPMENT("3313 Repair of electronic and optical equipment"),
    _3314_REPAIR_OF_ELECTRICAL_EQUIPMENT("3314 Repair of electrical equipment"),
    _3315_REPAIR_AND_MAINTENANCE_OF_SHIPS_AND_BOATS("3315 Repair and maintenance of ships and boats"),
    _3316_REPAIR_AND_MAINTENANCE_OF_AIRCRAFT_AND_SPACECRAFT("3316 Repair and maintenance of aircraft and spacecraft"),
    _3317_REPAIR_AND_MAINTENANCE_OF_OTHER_TRANSPORT_EQUIPMENT("3317 Repair and maintenance of other transport equipment"),
    _3319_REPAIR_OF_OTHER_EQUIPMENT("3319 Repair of other equipment"),
    _332_INSTALLATION_OF_INDUSTRIAL_MACHINERY_AND_EQUIPMENT("332 Installation of industrial machinery and equipment"),
    _3511_PRODUCTION_OF_ELECTRICITY("3511 Production of electricity"),
    _3512_TRANSMISSION_OF_ELECTRICITY("3512 Transmission of electricity"),
    _3513_DISTRIBUTION_OF_ELECTRICITY("3513 Distribution of electricity"),
    _3514_TRADE_OF_ELECTRICITY("3514 Trade of electricity"),
    _3521_MANUFACTURE_OF_GAS("3521 Manufacture of gas"),
    _3522_DISTRIBUTION_OF_GASEOUS_FUELS_THROUGH_MAINS("3522 Distribution of gaseous fuels through mains"),
    _3523_TRADE_OF_GAS_THROUGH_MAINS("3523 Trade of gas through mains"),
    _353_TEAM_AND_AIR_CONDITIONING_SUPPLY("353 team and air conditioning supply"),
    _360_WATER_COLLECTION_TREATMENT_AND_SUPPLY("360 Water collection, treatment and supply"),
    _370_SEWERAGE("370 Sewerage"),
    _3811_COLLECTION_OF_NON_HAZARDOUS_WASTE("3811 Collection of non-hazardous waste"),
    _3812_COLLECTION_OF_HAZARDOUS_WASTE("3812 Collection of hazardous waste"),
    _3821_TREATMENT_AND_DISPOSAL_OF_NON_HAZARDOUS_WASTE("3821 Treatment and disposal of non-hazardous waste"),
    _3822_TREATMENT_AND_DISPOSAL_OF_HAZARDOUS_WASTE("3822 Treatment and disposal of hazardous waste"),
    _3831_DISMANTLING_OF_WRECKS("3831 Dismantling of wrecks"),
    _3832_RECOVERY_OF_SORTED_MATERIALS("3832 Recovery of sorted materials"),
    _390_REMEDIATION_ACTIVITIES_AND_OTHER_WASTE_MANAGEMENT_SERVICES("390 Remediation activities and other waste management services"),
    _411_DEVELOPMENT_OF_BUILDING_PROJECTS("411 Development of building projects"),
    _412_CONSTRUCTION_OF_RESIDENTIAL_AND_NON_RESIDENTIAL_BUILDINGS("412 Construction of residential and non-residential buildings"),
    _4211_CONSTRUCTION_OF_ROADS_AND_MOTORWAYS("4211 Construction of roads and motorways"),
    _4212_CONSTRUCTION_OF_RAILWAYS_AND_UNDERGROUND_RAILWAYS("4212 Construction of railways and underground railways"),
    _4213_CONSTRUCTION_OF_BRIDGES_AND_TUNNELS("4213 Construction of bridges and tunnels"),
    _4221_CONSTRUCTION_OF_UTILITY_PROJECTS_FOR_FLUIDS("4221 Construction of utility projects for fluids"),
    _4222_CONSTRUCTION_OF_UTILITY_PROJECTS_FOR_ELECTRICITY_AND_TELECOMMUNICATIONS("4222 Construction of utility projects for electricity and telecommunications"),
    _4291_CONSTRUCTION_OF_WATER_PROJECTS("4291 Construction of water projects"),
    _4299_CONSTRUCTION_OF_OTHER_CIVIL_ENGINEERING_PROJECTS_N_E_C_("4299 Construction of other civil engineering projects n.e.c."),
    _4311_DEMOLITION("4311 Demolition"),
    _4312_SITE_PREPARATION("4312 Site preparation"),
    _4313_TEST_DRILLING_AND_BORING("4313 Test drilling and boring"),
    _4321_ELECTRICAL_INSTALLATION("4321 Electrical installation"),
    _4322_PLUMBING_HEAT_AND_AIR_CONDITIONING_INSTALLATION("4322 Plumbing, heat and air conditioning installation"),
    _4329_OTHER_CONSTRUCTION_INSTALLATION("4329 Other construction installation"),
    _4331_PLASTERING("4331 Plastering"),
    _4332_JOINERY_INSTALLATION("4332 Joinery installation"),
    _4333_FLOOR_AND_WALL_COVERING("4333 Floor and wall covering"),
    _4334_PAINTING_AND_GLAZING("4334 Painting and glazing"),
    _4339_OTHER_BUILDING_COMPLETION_AND_FINISHING("4339 Other building completion and finishing"),
    _4391_ROOFING_ACTIVITIES("4391 Roofing activities"),
    _4399_OTHER_SPECIALIZED_CONSTRUCTION_ACTIVITIES_N_E_C_("4399 Other specialised construction activities n.e.c."),
    _4511_SALE_OF_CARS_AND_LIGHT_MOTOR_VEHICLES("4511 Sale of cars and light motor vehicles"),
    _4519_SALE_OF_OTHER_MOTOR_VEHICLES("4519 Sale of other motor vehicles"),
    _452_MAINTENANCE_AND_REPAIR_OF_MOTOR_VEHICLES("452 Maintenance and repair of motor vehicles"),
    _4531_WHOLESOME_TRADE_OF_MOTOR_VEHICLE_PARTS_AND_ACCESSORIES("4531 Wholesale trade of motor vehicle parts and accessories"),
    _4532_RETAIL_TRADE_OF_MOTOR_VEHICLE_PARTS_AND_ACCESSORIES("4532 Retail trade of motor vehicle parts and accessories"),
    _454_SALE_MAINTENANCE_AND_REPAIR_OF_MOTORCYCLES_AND_RELATED_PARTS_AND_ACCESSORIES("454 Sale, maintenance and repair of motorcycles and related parts and accessories"),
    _4611_AGENTS_INVOLVED_IN_THE_SALE_OF_AGRICULTURAL_RAW_MATERIALS_LIVE_ANIMALS_TEXTILE_RAW_MATERIALS_AND_SEMI_FINISHED_GOODS("4611 Agents involved in the sale of agricultural raw materials, live animals, textile raw materials and semi-finished goods"),
    _4612_AGENTS_INVOLVED_IN_THE_SALE_OF_FUELS_ORES_METALS_AND_INDUSTRIAL_CHEMICALS("4612 Agents involved in the sale of fuels, ores, metals and industrial chemicals"),
    _4613_AGENTS_INVOLVED_IN_THE_SALE_OF_TIMBER_AND_BUILDING_MATERIALS("4613 Agents involved in the sale of timber and building materials"),
    _4614_AGENTS_INVOLVED_IN_THE_SALE_OF_MACHINERY_INDUSTRIAL_EQUIPMENT_SHIPS_AND_AIRCRAFT("4614 Agents involved in the sale of machinery, industrial equipment, ships and aircraft"),
    _4615_AGENTS_INVOLVED_IN_THE_SALE_OF_FURNITURE_HOUSEHOLD_GOODS_HARDWARE_AND_IRONMONGERY("4615 Agents involved in the sale of furniture, household goods, hardware and ironmongery"),
    _4616_AGENTS_INVOLVED_IN_THE_SALE_OF_TEXTILES_CLOTHING_FUR_FOOTWEAR_AND_LEATHER_GOODS("4616 Agents involved in the sale of textiles, clothing, fur, footwear and leather goods"),
    _4617_AGENTS_INVOLVED_IN_THE_SALE_OF_FOOD_BEVERAGES_AND_TOBACCO("4617 Agents involved in the sale of food, beverages and tobacco"),
    _4618_AGENTS_SPECIALISED_IN_THE_SALE_OF_OTHER_PARTICULAR_PRODUCTS("4618 Agents specialised in the sale of other particular products"),
    _4619_AGENTS_INVOLVED_IN_THE_SALE_OF_A_VARIETY_OF_GOODS("4619 Agents involved in the sale of a variety of goods"),
    _4621_WHOLESALE_OF_GRAIN_UNMANUFACTURED_TOBACCO_SEEDS_AND_ANIMAL_FEEDS("4621 Wholesale of grain, unmanufactured tobacco, seeds and animal feeds"),
    _4622_WHOLESALE_OF_FLOWERS_AND_PLANTS("4622 Wholesale of flowers and plants"),
    _4623_WHOLESALE_OF_LIVE_ANIMALS("4623 Wholesale of live animals"),
    _4624_WHOLESALE_OF_HIDES_SKINS_AND_LEATHER("4624 Wholesale of hides, skins and leather"),
    _4631_WHOLESALE_OF_FRUIT_AND_VEGETABLES("4631 Wholesale of fruit and vegetables"),
    _4632_WHOLESALE_OF_MEAT_AND_MEAT_PRODUCTS("4632 Wholesale of meat and meat products"),
    _4633_WHOLESALE_OF_DAIRY_PRODUCTS_EGGS_AND_EDIBLE_OILS_AND_FATS("4633 Wholesale of dairy products, eggs and edible oils and fats"),
    _4634_WHOLESALE_OF_BEVERAGES("4634 Wholesale of beverages"),
    _4635_WHOLESALE_OF_TOBACCO_PRODUCTS("4635 Wholesale of tobacco products"),
    _4636_WHOLESALE_OF_SUGAR_AND_CHOCOLATE_AND_SUGAR_CONFECTIONERY("4636 Wholesale of sugar and chocolate and sugar confectionery"),
    _4637_WHOLESALE_OF_COFFEE_TEA_COCOA_AND_SPICES("4637 Wholesale of coffee, tea, cocoa and spices"),
    _4638_WHOLESALE_OF_OTHER_FOOD_INCLUDING_FISH_CRUSTACEANS_AND_MOLLUSCS("4638 Wholesale of other food, including fish, crustaceans and molluscs"),
    _4639_NON_SPECIALISED_WHOLESALE_OF_FOOD_BEVERAGES_AND_TOBACCO("4639 Non-specialised wholesale of food, beverages and tobacco"),
    _4641_WHOLESALE_OF_TEXTILES("4641 Wholesale of textiles"),
    _4642_WHOLESALE_OF_CLOTHING_AND_FOOTWEAR("4642 Wholesale of clothing and footwear"),
    _4643_WHOLESALE_OF_ELECTRICAL_HOUSEHOLD_APPLIANCES("4643 Wholesale of electrical household appliances"),
    _4644_WHOLESALE_OF_CHINA_AND_GLASSWARE_AND_CLEANING_MATERIALS("4644 Wholesale of china and glassware and cleaning materials"),
    _4645_WHOLESALE_OF_PERFUME_AND_COSMETICS("4645 Wholesale of perfume and cosmetics"),
    _4646_WHOLESALE_OF_PHARMACEUTICAL_GOODS("4646 Wholesale of pharmaceutical goods"),
    _4647_WHOLESALE_OF_FURNITURE_CARPETS_AND_LIGHTING_EQUIPMENT("4647 Wholesale of furniture, carpets and lighting equipment"),
    _4648_WHOLESALE_OF_WATCHES_AND_JEWELLERY("4648 Wholesale of watches and jewellery"),
    _4649_WHOLESALE_OF_OTHER_HOUSEHOLD_GOODS("4649 Wholesale of other household goods"),
    _4651_WHOLESALE_OF_COMPUTERS_COMPUTER_PERIPHERAL_EQUIPMENT_AND_SOFTWARE("4651 Wholesale of computers, computer peripheral equipment and software"),
    _4652_WHOLESALE_OF_ELECTRONIC_AND_TELECOMMUNICATIONS_EQUIPMENT_AND_PARTS("4652 Wholesale of electronic and telecommunications equipment and parts"),
    _4661_WHOLESALE_OF_AGRICULTURAL_MACHINERY_EQUIPMENT_AND_SUPPLIES("4661 Wholesale of agricultural machinery, equipment and supplies"),
    _4662_WHOLESALE_OF_MACHINE_TOOLS("4662 Wholesale of machine tools"),
    _4663_WHOLESALE_OF_MINING_CONSTRUCTION_AND_CIVIL_ENGINEERING_MACHINERY("4663 Wholesale of mining, construction and civil engineering machinery"),
    _4664_WHOLESALE_OF_MACHINERY_FOR_THE_TEXTILE_INDUSTRY_AND_OF_SEWING_AND_KNITTING_MACHINES("4664 Wholesale of machinery for the textile industry and of sewing and knitting machines"),
    _4665_WHOLESALE_OF_OFFICE_FURNITURE("4665 Wholesale of office furniture"),
    _4666_WHOLESALE_OF_OTHER_OFFICE_MACHINERY_AND_EQUIPMENT("4666 Wholesale of other office machinery and equipment"),
    _4669_WHOLESALE_OF_OTHER_MACHINERY_AND_EQUIPMENT("4669 Wholesale of other machinery and equipment"),
    _4671_WHOLESALE_OF_SOLID_LIQUID_AND_GASEOUS_FUELS_AND_RELATED_PRODUCTS("4671 Wholesale of solid, liquid and gaseous fuels and related products"),
    _4672_WHOLESALE_OF_METALS_AND_METAL_ORES("4672 Wholesale of metals and metal ores"),
    _4673_WHOLESALE_OF_WOOD_CONSTRUCTION_MATERIALS_AND_SANITARY_EQUIPMENT("4673 Wholesale of wood, construction materials and sanitary equipment"),
    _4674_WHOLESALE_OF_HARDWARE_PLUMBING_AND_HEATING_EQUIPMENT_AND_SUPPLIES("4674 Wholesale of hardware, plumbing and heating equipment and supplies"),
    _4675_WHOLESALE_OF_CHEMICAL_PRODUCTS("4675 Wholesale of chemical products"),
    _4676_WHOLESALE_OF_OTHER_INTERMEDIATE_PRODUCTS("4676 Wholesale of other intermediate products"),
    _4677_WHOLESALE_OF_WASTE_AND_SCRAP("4677 Wholesale of waste and scrap"),
    _469_NON_SPECIALISED_WHOLESALE_TRADE("469 Non-specialised wholesale trade"),
    _4711_RETAIL_SALE_IN_NON_SPECIALISED_STORES_WITH_FOOD_BEVERAGES_OR_TOBACCO_PREDOMINATING("4711 Retail sale in non-specialised stores with food, beverages or tobacco predominating"),
    _4719_OTHER_RETAIL_SALE_IN_NON_SPECIALISED_STORES("4719 Other retail sale in non-specialised stores"),
    _4721_RETAIL_SALE_OF_FRUIT_AND_VEGETABLES_IN_SPECIALISED_STORES("4721 Retail sale of fruit and vegetables in specialised stores"),
    _4722_RETAIL_SALE_OF_MEAT_AND_MEAT_PRODUCTS_IN_SPECIALISED_STORES("4722 Retail sale of meat and meat products in specialised stores"),
    _4723_RETAIL_SALE_OF_FISH_CRUSTACEANS_AND_MOLLUSCS_IN_SPECIALISED_STORES("4723 Retail sale of fish, crustaceans and molluscs in specialised stores"),
    _4724_RETAIL_SALE_OF_BREAD_CAKES_FLOUR_CONFECTIONERY_AND_SUGAR_CONFECTIONERY_IN_SPECIALISED_STORES("4724 Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores"),
    _4725_RETAIL_SALE_OF_BEVERAGES_IN_SPECIALISED_STORES("4725 Retail sale of beverages in specialised stores"),
    _4726_RETAIL_SALE_OF_TOBACCO_PRODUCTS_IN_SPECIALISED_STORES("4726 Retail sale of tobacco products in specialised stores"),
    _4729_OTHER_RETAIL_SALE_OF_FOOD_IN_SPECIALISED_STORES("4729 Other retail sale of food in specialised stores"),
    _473_RETAIL_SALE_OF_AUTOMOTIVE_FUEL_IN_SPECIALISED_STORES("473 Retail sale of automotive fuel in specialised stores"),
    _4741_RETAIL_SALE_OF_COMPUTERS_PERIPHERAL_UNITS_AND_SOFTWARE_IN_SPECIALISED_STORES("4741 Retail sale of computers, peripheral units and software in specialised stores"),
    _4742_RETAIL_SALE_OF_TELECOMMUNICATIONS_EQUIPMENT_IN_SPECIALISED_STORES("4742 Retail sale of telecommunications equipment in specialised stores"),
    _4743_RETAIL_SALE_OF_AUDIO_AND_VIDEO_EQUIPMENT_IN_SPECIALISED_STORES("4743 Retail sale of audio and video equipment in specialised stores"),
    _4751_RETAIL_SALE_OF_TEXTILES_IN_SPECIALISED_STORES("4751 Retail sale of textiles in specialised stores"),
    _4752_RETAIL_SALE_OF_HARDWARE_PAINTS_AND_GLASS_IN_SPECIALISED_STORES("4752 Retail sale of hardware, paints and glass in specialised stores"),
    _4753_RETAIL_SALE_OF_CARPETS_RUGS_WALL_AND_FLOOR_COVERINGS_IN_SPECIALISED_STORES("4753 Retail sale of carpets, rugs, wall and floor coverings in specialised stores"),
    _4754_RETAIL_SALE_OF_ELECTRICAL_HOUSEHOLD_APPLIANCES_IN_SPECIALISED_STORES("4754 Retail sale of electrical household appliances in specialised stores"),
    _4759_RETAIL_SALE_OF_FURNITURE_LIGHTING_EQUIPMENT_AND_OTHER_HOUSEHOLD_ARTICLES_IN_SPECIALISED_STORES("4759 Retail sale of furniture, lighting equipment and other household articles in specialised stores"),
    _4761_RETAIL_SALE_OF_BOOKS_IN_SPECIALISED_STORES("4761 Retail sale of books in specialised stores"),
    _4762_RETAIL_SALE_OF_NEWSPAPERS_AND_STATIONERY_IN_SPECIALISED_STORES("4762 Retail sale of newspapers and stationery in specialised stores"),
    _4763_RETAIL_SALE_OF_MUSIC_AND_VIDEO_RECORDINGS_IN_SPECIALISED_STORES("4763 Retail sale of music and video recordings in specialised stores"),
    _4764_RETAIL_SALE_OF_SPORTING_EQUIPMENT_IN_SPECIALISED_STORES("4764 Retail sale of sporting equipment in specialised stores"),
    _4765_RETAIL_SALE_OF_GAMES_AND_TOYS_IN_SPECIALISED_STORES("4765 Retail sale of games and toys in specialised stores"),
    _4771_RETAIL_SALE_OF_CLOTHING_IN_SPECIALISED_STORES("4771 Retail sale of clothing in specialised stores"),
    _4772_RETAIL_SALE_OF_FOOTWEAR_AND_LEATHER_GOODS_IN_SPECIALISED_STORES("4772 Retail sale of footwear and leather goods in specialised stores"),
    _4773_DISPENSING_CHEMIST_IN_SPECIALISED_STORES("4773 Dispensing chemist in specialised stores"),
    _4774_RETAIL_SALE_OF_MEDICAL_AND_ORTHOPAEDIC_GOODS_IN_SPECIALISED_STORES("4774 Retail sale of medical and orthopaedic goods in specialised stores"),
    _4775_RETAIL_SALE_OF_COSMETIC_AND_TOILET_ARTICLES_IN_SPECIALISED_STORES("4775 Retail sale of cosmetic and toilet articles in specialised stores"),
    _4776_RETAIL_SALE_OF_FLOWERS_PLANTS_SEEDS_FERTILISERS_PET_ANIMALS_AND_PET_FOOD_IN_SPECIALISED_STORES("4776 Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores"),
    _4777_RETAIL_SALE_OF_WATCHES_AND_JEWELLERY_IN_SPECIALISED_STORES("4777 Retail sale of watches and jewellery in specialised stores"),
    _4778_OTHER_RETAIL_SALE_OF_NEW_GOODS_IN_SPECIALISED_STORES("4778 Other retail sale of new goods in specialised stores"),
    _4779_RETAIL_SALE_OF_SECOND_HAND_GOODS_IN_STORES("4779 Retail sale of second-hand goods in stores"),
    _4781_RETAIL_SALE_VIA_STALLS_AND_MARKETS_OF_FOOD_BEVERAGES_AND_TOBACCO_PRODUCTS("4781 Retail sale via stalls and markets of food, beverages and tobacco products"),
    _4782_RETAIL_SALE_VIA_STALLS_AND_MARKETS_OF_TEXTILES_CLOTHING_AND_FOOTWEAR("4782 Retail sale via stalls and markets of textiles, clothing and footwear"),
    _4789_RETAIL_SALE_VIA_STALLS_AND_MARKETS_OF_OTHER_GOODS("4789 Retail sale via stalls and markets of other goods"),
    _4791_RETAIL_SALE_VIA_MAIL_ORDER_HOUSES_OR_VIA_INTERNET("4791 Retail sale via mail order houses or via Internet"),
    _4799_OTHER_RETAIL_SALE_NOT_IN_STORES_STALLS_OR_MARKETS("4799 Other retail sale not in stores, stalls or markets"),
    _491_PASSENGER_RAIL_TRANSPORT_INTERURBAN("491 Passenger rail transport, interurban"),
    _492_FREIGHT_RAIL_TRANSPORT("492 Freight rail transport"),
    _4931_URBAN_AND_SUBURBAN_PASSENGER_LAND_TRANSPORT("4931 Urban and suburban passenger land transport"),
    _4932_TAXI_OPERATION("4932 Taxi operation"),
    _4939_OTHER_PASSENGER_LAND_TRANSPORT_N_E_C_("4939 Other passenger land transport n.e.c."),
    _4941_FREIGHT_TRANSPORT_BY_ROAD("4941 Freight transport by road"),
    _4942_REMOVAL_SERVICES("4942 Removal services"),
    _495_TRANSPORT_VIA_PIPELINE("495 Transport via pipeline"),
    _501_SEA_AND_COASTAL_PASSENGER_WATER_TRANSPORT("501 Sea and coastal passenger water transport"),
    _502_SEA_AND_COASTAL_FREIGHT_WATER_TRANSPORT("502 Sea and coastal freight water transport"),
    _503_INLAND_PASSENGER_WATER_TRANSPORT("503 Inland passenger water transport"),
    _504_INLAND_FREIGHT_WATER_TRANSPORT("504 Inland freight water transport"),
    _511_PASSENGER_AIR_TRANSPORT("511 Passenger air transport"),
    _5121_FREIGHT_AIR_TRANSPORT("5121 Freight air transport"),
    _5122_SPACE_TRANSPORT("5122 Space transport"),
    _521_WAREHOUSING_AND_STORAGE("521 Warehousing and storage"),
    _5221_SERVICE_ACTIVITIES_INCIDENTAL_TO_LAND_TRANSPORTATION("5221 Service activities incidental to land transportation"),
    _5222_SERVICE_ACTIVITIES_INCIDENTAL_TO_WATER_TRANSPORTATION("5222 Service activities incidental to water transportation"),
    _5223_SERVICE_ACTIVITIES_INCIDENTAL_TO_AIR_TRANSPORTATION("5223 Service activities incidental to air transportation"),
    _5224_CARGO_HANDLING("5224 Cargo handling"),
    _5229_OTHER_TRANSPORTATION_SUPPORT_ACTIVITIES("5229 Other transportation support activities"),
    _531_POSTAL_ACTIVITIES_UNDER_UNIVERSAL_SERVICE_OBLIGATION("531 Postal activities under universal service obligation"),
    _532_OTHER_POSTAL_AND_COURIER_ACTIVITIES("532 Other postal and courier activities"),
    _551_HOTELS_AND_SIMILAR_ACCOMMODATION("551 Hotels and similar accommodation"),
    _552_HOLIDAY_AND_OTHER_SHORT_STAY_ACCOMMODATION("552 Holiday and other short-stay accommodation"),
    _553_CAMPING_GROUNDS_RECREATIONAL_VEHICLE_PARKS_AND_TRAILER_PARKS("553 Camping grounds, recreational vehicle parks and trailer parks"),
    _559_OTHER_ACCOMMODATION("559 Other accommodation"),
    _561_RESTAURANTS_AND_MOBILE_FOOD_SERVICE_ACTIVITIES("561 Restaurants and mobile food service activities"),
    _5621_EVENT_CATERING_ACTIVITIES("5621 Event catering activities"),
    _5629_OTHER_FOOD_SERVICE_ACTIVITIES("5629 Other food service activities"),
    _563_BEVERAGE_SERVING_ACTIVITIES("563 Beverage serving activities"),
    _5811_BOOK_PUBLISHING("5811 Book publishing"),
    _5812_PUBLISHING_OF_DIRECTORIES_AND_MAILING_LISTS("5812 Publishing of directories and mailing lists"),
    _5813_PUBLISHING_OF_NEWSPAPERS("5813 Publishing of newspapers"),
    _5814_PUBLISHING_OF_JOURNALS_AND_PERIODICALS("5814 Publishing of journals and periodicals"),
    _5819_OTHER_PUBLISHING_ACTIVITIES("5819 Other publishing activities"),
    _5821_PUBLISHING_OF_COMPUTER_GAMES("5821 Publishing of computer games"),
    _5829_OTHER_SOFTWARE_PUBLISHING("5829 Other software publishing"),
    _5911_MOTION_PICTURE_VIDEO_AND_TELEVISION_PROGRAMME_PRODUCTION_ACTIVITIES("5911 Motion picture, video and television programme production activities"),
    _5912_MOTION_PICTURE_VIDEO_AND_TELEVISION_PROGRAMME_POST_PRODUCTION_ACTIVITIES("5912 Motion picture, video and television programme post-production activities"),
    _5913_MOTION_PICTURE_VIDEO_AND_TELEVISION_PROGRAMME_DISTRIBUTION_ACTIVITIES("5913 Motion picture, video and television programme distribution activities"),
    _5914_MOTION_PICTURE_PROJECTION_ACTIVITIES("5914 Motion picture projection activities"),
    _592_SOUND_RECORDING_AND_MUSIC_PUBLISHING_ACTIVITIES("592 sound recording and music publishing activities"),
    _601_RADIO_BROADCASTING("601 Radio broadcasting"),
    _602_TELEVISION_PROGRAMMING_AND_BROADCASTING_ACTIVITIES("602 Television programming and broadcasting activities"),
    _611_WIRED_TELECOMMUNICATIONS_ACTIVITIES("611 Wired telecommunications activities"),
    _612_WIRELESS_TELECOMMUNICATIONS_ACTIVITIES("612 Wireless telecommunications activities"),
    _613_SATELLITE_TELECOMMUNICATIONS_ACTIVITIES("613 Satellite telecommunications activities"),
    _619_OTHER_TELECOMMUNICATIONS_ACTIVITIES("619 Other telecommunications activities"),
    _6201_COMPUTER_PROGRAMMING_ACTIVITIES("6201 Computer programming activities"),
    _6202_COMPUTER_CONSULTANCY_ACTIVITIES("6202 Computer consultancy activities"),
    _6203_COMPUTER_FACILITIES_MANAGEMENT_ACTIVITIES("6203 Computer facilities management activities"),
    _6209_OTHER_INFORMATION_TECHNOLOGY_AND_COMPUTER_SERVICE_ACTIVITIES("6209 Other information technology and computer service activities"),
    _6311_DATA_PROCESSING_HOSTING_AND_RELATED_ACTIVITIES("6311 Data processing, hosting and related activities"),
    _6312_WEB_PORTALS("6312 Web portals"),
    _6391_NEWS_AGENCY_ACTIVITIES("6391 News agency activities"),
    _6399_OTHER_INFORMATION_SERVICE_ACTIVITIES_N_E_C_("6399 Other information service activities n.e.c."),
    _6411_CENTRAL_BANKING("6411 Central banking"),
    _6419_OTHER_MONETARY_INTERMEDIATION("6419 Other monetary intermediation"),
    _642_ACTIVITIES_OF_HOLDING_COMPANIES("642 Activities of holding companies"),
    _643_TRUSTS_FUNDS_AND_SIMILAR_FINANCIAL_ENTITIES("643 Trusts, funds and similar financial entities"),
    _6491_FINANCIAL_LEASING("6491 Financial leasing"),
    _6492_OTHER_CREDIT_GRANTING("6492 Other credit granting"),
    _6499_OTHER_FINANCIAL_SERVICE_ACTIVITIES_EXCEPT_INSURANCE_AND_PENSION_FUNDING_N_E_C_("6499 Other financial service activities, except insurance and pension funding n.e.c."),
    _6511_LIFE_INSURANCE("6511 Life insurance"),
    _6512_NON_LIFE_INSURANCE("6512 Non-life insurance"),
    _652_REINSURANCE("652 Reinsurance"),
    _653_PENSION_FUNDING("653 Pension funding"),
    _6611_ADMINISTRATION_OF_FINANCIAL_MARKETS("6611 Administration of financial markets"),
    _6612_SECURITY_AND_COMMODITY_CONTRACTS_BROKERAGE("6612 Security and commodity contracts brokerage"),
    _6619_OTHER_ACTIVITIES_AUXILIARY_TO_FINANCIAL_SERVICES_EXCEPT_INSURANCE_AND_PENSION_FUNDING("6619 Other activities auxiliary to financial services, except insurance and pension funding"),
    _6621_RISK_AND_DAMAGE_EVALUATION("6621 Risk and damage evaluation"),
    _6622_ACTIVITIES_OF_INSURANCE_AGENTS_AND_BROKERS("6622 Activities of insurance agents and brokers"),
    _6629_OTHER_ACTIVITIES_AUXILIARY_TO_INSURANCE_AND_PENSION_FUNDING("6629 Other activities auxiliary to insurance and pension funding"),
    _663_FUND_MANAGEMENT_ACTIVITIES("663 Fund management activities"),
    _681_BUYING_AND_SELLING_OF_OWN_REAL_ESTATE("681 Buying and selling of own real estate"),
    _682_RENTING_AND_OPERATING_OF_OWN_OR_LEASED_REAL_ESTATE("682 Renting and operating of own or leased real estate"),
    _6831_REAL_ESTATE_AGENCIES("6831 Real estate agencies"),
    _6832_MANAGEMENT_OF_REAL_ESTATE_ON_A_FEE_OR_CONTRACT_BASIS("6832 Management of real estate on a fee or contract basis"),
    _691_LEGAL_ACTIVITIES("691 Legal activities"),
    _692_ACCOUNTING_BOOKKEEPING_AND_AUDITING_ACTIVITIES_TAX_CONSULTANCY("692 Accounting, bookkeeping and auditing activities; tax consultancy"),
    _701_ACTIVITIES_OF_HEAD_OFFICES("701 Activities of head offices"),
    _7021_PUBLIC_RELATIONS_AND_COMMUNICATION_ACTIVITIES("7021 Public relations and communication activities"),
    _7022_BUSINESS_AND_OTHER_MANAGEMENT_CONSULTANCY_ACTIVITIES("7022 Business and other management consultancy activities"),
    _7111_ARCHITECTURAL_ACTIVITIES("7111 Architectural activities"),
    _7112_ENGINEERING_ACTIVITIES_AND_RELATED_TECHNICAL_CONSULTANCY("7112 Engineering activities and related technical consultancy"),
    _712_TECHNICAL_TESTING_AND_ANALYSIS("712 Technical testing and analysis"),
    _7211_RESEARCH_AND_EXPERIMENTAL_DEVELOPMENT_ON_BIOTECHNOLOGY("7211 Research and experimental development on biotechnology"),
    _7219_OTHER_RESEARCH_AND_EXPERIMENTAL_DEVELOPMENT_ON_NATURAL_SCIENCES_AND_ENGINEERING("7219 Other research and experimental development on natural sciences and engineering"),
    _722_RESEARCH_AND_EXPERIMENTAL_DEVELOPMENT_ON_SOCIAL_SCIENCES_AND_HUMANITIES("722 Research and experimental development on social sciences and humanities"),
    _7311_ADVERTISING_AGENCIES("7311 Advertising agencies"),
    _7312_MEDIA_REPRESENTATION("7312 Media representation"),
    _732_MARKET_RESEARCH_AND_PUBLIC_OPINION_POLLING("732 Market research and public opinion polling"),
    _741_SPECIALISED_DESIGN_ACTIVITIES("741 Specialised design activities"),
    _742_PHOTOGRAPHIC_ACTIVITIES("742 Photographic activities"),
    _743_TRANSLATION_AND_INTERPRETATION_ACTIVITIES("743 Translation and interpretation activities"),
    _749_OTHER_PROFESSIONAL_SCIENTIFIC_AND_TECHNICAL_ACTIVITIES_N_E_C_("749 Other professional, scientific and technical activities n.e.c."),
    _750_VETERINARY_ACTIVITIES("750 Veterinary activities"),
    _7711_RENTING_AND_LEASING_OF_CARS_AND_LIGHT_MOTOR_VEHICLES("7711 Renting and leasing of cars and light motor vehicles"),
    _7712_RENTING_AND_LEASING_OF_TRUCKS("7712 Renting and leasing of trucks"),
    _7721_RENTING_AND_LEASING_OF_RECREATIONAL_AND_SPORTS_GOODS("7721 Renting and leasing of recreational and sports goods"),
    _7722_RENTING_OF_VIDEO_TAPES_AND_DISKS("7722 Renting of video tapes and disks"),
    _7729_RENTING_AND_LEASING_OF_OTHER_PERSONAL_AND_HOUSEHOLD_GOODS("7729 Renting and leasing of other personal and household goods"),
    _7731_RENTING_AND_LEASING_OF_AGRICULTURAL_MACHINERY_AND_EQUIPMENT("7731 Renting and leasing of agricultural machinery and equipment"),
    _7732_RENTING_AND_LEASING_OF_CONSTRUCTION_AND_CIVIL_ENGINEERING_MACHINERY_AND_EQUIPMENT("7732 Renting and leasing of construction and civil engineering machinery and equipment"),
    _7733_RENTING_AND_LEASING_OF_OFFICE_MACHINERY_AND_EQUIPMENT_INCLUDING_COMPUTERS("7733 Renting and leasing of office machinery and equipment (including computers)"),
    _7734_RENTING_AND_LEASING_OF_WATER_TRANSPORT_EQUIPMENT("7734 Renting and leasing of water transport equipment"),
    _7735_RENTING_AND_LEASING_OF_AIR_TRANSPORT_EQUIPMENT("7735 Renting and leasing of air transport equipment"),
    _7739_RENTING_AND_LEASING_OF_OTHER_MACHINERY_EQUIPMENT_AND_TANGIBLE_GOODS_N_E_C_("7739 Renting and leasing of other machinery, equipment and tangible goods n.e.c."),
    _774_LEASING_OF_INTELLECTUAL_PROPERTY_AND_SIMILAR_PRODUCTS_EXCEPT_COPYRIGHTED_WORKS("774 Leasing of intellectual property and similar products, except copyrighted works"),
    _781_ACTIVITIES_OF_EMPLOYMENT_PLACEMENT_AGENCIES("781 Activities of employment placement agencies"),
    _782_TEMPORARY_EMPLOYMENT_AGENCY_ACTIVITIES("782 Temporary employment agency activities"),
    _783_OTHER_HUMAN_RESOURCES_PROVISION("783 Other human resources provision"),
    _7911_TRAVEL_AGENCY_ACTIVITIES("7911 Travel agency activities"),
    _7912_TOUR_OPERATOR_ACTIVITIES("7912 Tour operator activities"),
    _799_OTHER_RESERVATION_SERVICE_AND_RELATED_ACTIVITIES("799 Other reservation service and related activities"),
    _801_PRIVATE_SECURITY_ACTIVITIES("801 Private security activities"),
    _802_SECURITY_SYSTEMS_SERVICE_ACTIVITIES("802 Security systems service activities"),
    _803_INVESTIGATION_ACTIVITIES("803 Investigation activities"),
    _811_COMBINED_FACILITIES_SUPPORT_ACTIVITIES("811 Combined facilities support activities"),
    _8121_GENERAL_CLEANING_OF_BUILDINGS("8121 General cleaning of buildings"),
    _8122_OTHER_BUILDING_AND_INDUSTRIAL_CLEANING_ACTIVITIES("8122 Other building and industrial cleaning activities"),
    _8129_OTHER_CLEANING_ACTIVITIES("8129 Other cleaning activities"),
    _813_LANDSCAPE_SERVICE_ACTIVITIES("813 Landscape service activities"),
    _8211_COMBINED_OFFICE_ADMINISTRATIVE_SERVICE_ACTIVITIES("8211 Combined office administrative service activities"),
    _8219_PHOTOCOPYING_DOCUMENT_PREPARATION_AND_OTHER_SPECIALISED_OFFICE_SUPPORT_ACTIVITIES("8219 Photocopying, document preparation and other specialised office support activities"),
    _822_ACTIVITIES_OF_CALL_CENTRES("822 Activities of call centres"),
    _829_ORGANISATION_OF_CONVENTIONS_AND_TRADE_SHOWS("829 Organisation of conventions and trade shows"),
    _8291_ACTIVITIES_OF_COLLECTION_AGENCIES_AND_CREDIT_BUREAUS("8291 Activities of collection agencies and credit bureaus"),
    _8292_PACKAGING_ACTIVITIES("8292 Packaging activities"),
    _8299_OTHER_BUSINESS_SUPPORT_SERVICE_ACTIVITIES_N_E_C_("8299 Other business support service activities n.e.c."),
    _8411_GENERAL_PUBLIC_ADMINISTRATION_ACTIVITIES("8411 General public administration activities"),
    _8412_REGULATION_OF_THE_ACTIVITIES_OF_PROVIDING_HEALTH_CARE_EDUCATION_CULTURAL_SERVICES_AND_OTHER_SOCIAL_SERVICES_EXCEPT_SOCIAL_SECURITY("8412 Regulation of the activities of providing health care, education, cultural services and other social services, except social security"),
    _8413_REGULATION_OF_AND_CONTRIBUTION_TO_MORE_EFFICIENT_OPERATION_OF_BUSINESSES("8413 Regulation of and contribution to more efficient operation of businesses"),
    _8421_FOREIGN_AFFAIRS("8421 Foreign affairs"),
    _8422_DEFENCE_ACTIVITIES("8422 Defence activities"),
    _8423_JUSTICE_AND_JUDICIAL_ACTIVITIES("8423 Justice and judicial activities"),
    _8424_PUBLIC_ORDER_AND_SAFETY_ACTIVITIES("8424 Public order and safety activities"),
    _8425_FIRE_SERVICE_ACTIVITIES("8425 Fire service activities"),
    _843_COMPULSORY_SOCIAL_SECURITY_ACTIVITIES("843 Compulsory social security activities"),
    _851_PRE_PRIMARY_EDUCATION("851 Pre-primary education"),
    _852_PRIMARY_EDUCATION("852 Primary education"),
    _8531_GENERAL_SECONDARY_EDUCATION("8531 General secondary education"),
    _8532_TECHNICAL_AND_VOCATIONAL_SECONDARY_EDUCATION("8532 Technical and vocational secondary education"),
    _8541_POST_SECONDARY_NON_TERTIARY_EDUCATION("8541 Post-secondary non-tertiary education"),
    _8542_TERTIARY_EDUCATION("8542 Tertiary education"),
    _8551_SPORTS_AND_RECREATION_EDUCATION("8551 Sports and recreation education"),
    _8552_CULTURAL_EDUCATION("8552 Cultural education"),
    _8553_DRIVING_SCHOOL_ACTIVITIES("8553 Driving school activities"),
    _8559_OTHER_EDUCATION_N_E_C_("8559 Other education n.e.c."),
    _856_EDUCATIONAL_SUPPORT_ACTIVITIES("856 Educational support activities"),
    _861_HOSPITAL_ACTIVITIES("861 Hospital activities"),
    _8621_GENERAL_MEDICAL_PRACTICE_ACTIVITIES("8621 General medical practice activities"),
    _8622_SPECIALIST_MEDICAL_PRACTICE_ACTIVITIES("8622 Specialist medical practice activities"),
    _8623_DENTAL_PRACTICE_ACTIVITIES("8623 Dental practice activities"),
    _869_OTHER_HUMAN_HEALTH_ACTIVITIES("869 Other human health activities"),
    _871_RESIDENTIAL_NURSING_CARE_ACTIVITIES("891 Residential nursing care activities"),
    _872_RESIDENTIAL_CARE_ACTIVITIES_FOR_MENTAL_RETARDATION_MENTAL_HEALTH_AND_SUBSTANCE_ABUSE("872 Residential care activities for mental retardation, mental health and substance abuse"),
    _873_RESIDENTIAL_CARE_ACTIVITIES_FOR_THE_ELDERLY_AND_DISABLED("873 Residential care activities for the elderly and disabled"),
    _879_OTHER_RESIDENTIAL_CARE_ACTIVITIES("879 Other residential care activities"),
    _881_SOCIAL_WORK_ACTIVITIES_WITHOUT_ACCOMMODATION_FOR_THE_ELDERLY_AND_DISABLED("881 Social work activities without accommodation for the elderly and disabled"),
    _8891_CHILD_DAY_CARE_ACTIVITIES("8891 Child day-care activities"),
    _8899_OTHER_SOCIAL_WORK_ACTIVITIES_WITHOUT_ACCOMMODATION_N_E_C_("8899 Other social work activities without accommodation n.e.c."),
    _9001_PERFORMING_ARTS("9001 Performing arts"),
    _9002_SUPPORT_ACTIVITIES_TO_PERFORMING_ARTS("9002 Support activities to performing arts"),
    _9003_ARTISTIC_CREATION("9003 Artistic creation"),
    _9004_OPERATION_OF_ARTS_FACILITIES("9004 Operation of arts facilities"),
    _9101_LIBRARY_AND_ARCHIVES_ACTIVITIES("9101 Library and archives activities"),
    _9102_MUSEUMS_ACTIVITIES("9102 Museums activities"),
    _9103_OPERATION_OF_HISTORICAL_SITES_AND_BUILDINGS_AND_SIMILAR_VISITOR_ATTRACTIONS("9103 Operation of historical sites and buildings and similar visitor attractions"),
    _9104_BOTANICAL_AND_ZOOLOGICAL_GARDENS_AND_NATURE_RESERVES_ACTIVITIES("9104 Botanical and zoological gardens and nature reserves activities"),
    _920_GAMBLING_AND_BETTING_ACTIVITIES("920 Gambling and betting activities"),
    _9311_OPERATION_OF_SPORTS_FACILITIES("9311 Operation of sports facilities"),
    _9312_ACTIVITIES_OF_SPORT_CLUBS("9312 Activities of sport clubs"),
    _9313_FITNESS_FACILITIES("9313 Fitness facilities"),
    _9319_OTHER_SPORTS_ACTIVITIES("9319 Other sports activities"),
    _9321_ACTIVITIES_OF_AMUSEMENT_PARKS_AND_THEME_PARKS("9321 Activities of amusement parks and theme parks"),
    _9329_OTHER_AMUSEMENT_AND_RECREATION_ACTIVITIES("9329 Other amusement and recreation activities"),
    _9411_ACTIVITIES_OF_BUSINESS_AND_EMPLOYES_MEMBERSHIP_ORGANIZATIONS("9411 Activities of business and employers membership organisations"),
    _9412_ACTIVITIES_OF_PROFESSIONAL_MEMBERSHIP_ORGANIZATIONS("9412 Activities of professional membership organisations"),
    _942_ACTIVITIES_OF_TRADE_UNIONS("942 Activities of trade unions"),
    _9491_ACTIVITIES_OF_RELIGIOUS_ORGANIZATIONS("9491 Activities of religious organisations"),
    _9492_ACTIVITIES_OF_POLITICAL_ORGANIZATIONS("9492 Activities of political organisations"),
    _9499_ACTIVITIES_OF_OTHER_MEMBERSHIP_ORGANIZATIONS_N_E_C_("9499 Activities of other membership organisations n.e.c."),
    _9511_REPAIR_OF_COMPUTERS_AND_PERIPHERAL_EQUIPMENT("9511 Repair of computers and peripheral equipment"),
    _9512_REPAIR_OF_COMMUNICATION_EQUIPMENT("9512 Repair of communication equipment"),
    _9521_REPAIR_OF_CONSUMER_ELECTRONICS("9521 Repair of consumer electronics"),
    _9522_REPAIR_OF_HOUSEHOLD_APPLIANCES_AND_HOME_AND_GARDEN_EQUIPMENT("9522 Repair of household appliances and home and garden equipment"),
    _9523_REPAIR_OF_FOOTWEAR_AND_LEATHER_GOODS("9523 Repair of footwear and leather goods"),
    _9524_REPAIR_OF_FURNITURE_AND_HOME_FURNISHINGS("9524 Repair of furniture and home furnishings"),
    _9525_REPAIR_OF_WATCHES_CLOCKS_AND_JEWELLERY("9525 Repair of watches, clocks and jewellery"),
    _9529_REPAIR_OF_OTHER_PERSONAL_AND_HOUSEHOLD_GOODS("9529 Repair of other personal and household goods"),
    _9601_WASHING_AND_DRY_CLEANING_OF_TEXTILE_AND_FUR_PRODUCTS("9601 Washing and (dry-)cleaning of textile and fur products"),
    _9602_HAIRDRESSING_AND_OTHER_BEAUTY_TREATMENT("9602 Hairdressing and other beauty treatment"),
    _9603_FUNERAL_AND_RELATED_ACTIVITIES("9603 Funeral and related activities"),
    _9604_PHYSICAL_WELL_BEING_ACTIVITIES("9604 Physical well-being activities"),
    _9609_OTHER_PERSONAL_SERVICE_ACTIVITIES_N_E_C("9609 Other personal service activities n.e.c."),
    _970_ACTIVITIES_OF_HOUSEHOLDS_AS_EMPLOYERS_OF_DOMESTIC_PERSONNEL("970 Activities of households as employers of domestic personnel"),
    _981_UNDIFFERENTIATED_GOODS_PRODUCING_ACTIVITIES_OF_PRIVATE_HOUSEHOLDS_FOR_OWN_USE("981 Undifferentiated goods-producing activities of private households for own use"),
    _982_UNDIFFERENTIATED_SERVICE_PRODUCING_ACTIVITIES_OF_PRIVATE_HOUSEHOLDS_FOR_OWN_USE("982 Undifferentiated service-producing activities of private households for own use"),
    _990_ACTIVITIES_OF_EXTRATERRITORIAL_ORGANIZATIONS_AND_BODIES("990 Activities of extraterritorial organisations and bodies");

    private final String description;
}
