import {
  AuthorityManagePermissionDTO,
  RegulatorUserDTO,
  RegulatorUsersAuthoritiesInfoDTO,
  UserStatusDTO,
} from 'pmrv-api';

export const mockRegulatorsRouteData: { regulators: RegulatorUsersAuthoritiesInfoDTO } = {
  regulators: {
    caUsers: [
      {
        userId: '1reg',
        firstName: 'Alfyn',
        lastName: 'Octo',
        authorityStatus: 'DISABLED',
        locked: false,
        authorityCreationDate: '2020-12-14T12:38:12.846716Z',
      },
      {
        userId: '2reg',
        firstName: 'Therion',
        lastName: 'Path',
        authorityStatus: 'ACTIVE',
        locked: true,
        authorityCreationDate: '2020-12-15T12:38:12.846716Z',
      },
      {
        userId: '3reg',
        firstName: 'Olberik',
        lastName: 'Traveler',
        authorityStatus: 'ACTIVE',
        locked: true,
        authorityCreationDate: '2020-11-10T12:38:12.846716Z',
      },
      {
        userId: '4reg',
        firstName: 'andrew',
        lastName: 'webber',
        authorityStatus: 'ACTIVE',
        locked: false,
        authorityCreationDate: '2021-01-10T12:38:12.846716Z',
      },
      {
        userId: '5reg',
        firstName: 'William',
        lastName: 'Walker',
        authorityStatus: 'PENDING',
        locked: true,
        authorityCreationDate: '2021-02-8T12:38:12.846716Z',
      },
    ],
    editable: true,
  },
};

export const mockRegulatorUserStatus: UserStatusDTO = {
  loginStatus: 'ENABLED',
  roleType: 'REGULATOR',
  userId: '111',
};

export const mockRegulatorUser: {
  user: RegulatorUserDTO;
  permissions: AuthorityManagePermissionDTO;
} = {
  user: {
    email: 'test@host.com',
    firstName: 'John',
    lastName: 'Doe',
    jobTitle: 'developer',
    phoneNumber: '23456',
    mobileNumber: '55444',
    signature: {
      name: 'mySignature.bmp',
      uuid: '60fe9548-ac65-492a-b057-60033b0fbbed',
    },
  },
  permissions: {
    editable: true,
    permissions: {
      ADD_OPERATOR_ADMIN: 'EXECUTE',
      ASSIGN_REASSIGN_TASKS: 'NONE',
      MANAGE_USERS_AND_CONTACTS: 'NONE',
      MANAGE_VERIFICATION_BODIES: 'NONE',
      REVIEW_INSTALLATION_ACCOUNT: 'VIEW_ONLY',
      REVIEW_PERMIT_APPLICATION: 'VIEW_ONLY',
      PEER_REVIEW_PERMIT_APPLICATION: 'VIEW_ONLY',
      REVIEW_PERMIT_SURRENDER: 'VIEW_ONLY',
      PEER_REVIEW_PERMIT_SURRENDER: 'VIEW_ONLY',
      SUBMIT_PERMIT_REVOCATION: 'VIEW_ONLY',
      PEER_REVIEW_PERMIT_REVOCATION: 'VIEW_ONLY',
      REVIEW_PERMIT_NOTIFICATION: 'VIEW_ONLY',
      PEER_REVIEW_PERMIT_NOTIFICATION: 'VIEW_ONLY',
      SUBMIT_REVIEW_PERMIT_VARIATION: 'VIEW_ONLY',
      PEER_REVIEW_PERMIT_VARIATION: 'VIEW_ONLY',
      REVIEW_AER: 'VIEW_ONLY',
    },
  },
};

export const mockRegulatorRolePermissions = [
  'REVIEW_INSTALLATION_ACCOUNT',
  'MANAGE_USERS_AND_CONTACTS',
  'MANAGE_VERIFICATION_BODIES',
  'ADD_OPERATOR_ADMIN',
  'ASSIGN_REASSIGN_TASKS',
  'REVIEW_PERMIT_APPLICATION',
  'PEER_REVIEW_PERMIT_APPLICATION',
  'REVIEW_PERMIT_SURRENDER',
  'PEER_REVIEW_PERMIT_SURRENDER',
  'SUBMIT_PERMIT_REVOCATION',
  'PEER_REVIEW_PERMIT_REVOCATION',
  'REVIEW_PERMIT_NOTIFICATION',
  'PEER_REVIEW_PERMIT_NOTIFICATION',
  'SUBMIT_REVIEW_PERMIT_VARIATION',
  'PEER_REVIEW_PERMIT_VARIATION',
  'REVIEW_AER',
];

export const mockRegulatorBasePermissions = [
  {
    name: 'Regulator admin team',
    code: 'regulator_admin_team',
    rolePermissions: {
      REVIEW_INSTALLATION_ACCOUNT: 'VIEW_ONLY',
      MANAGE_USERS_AND_CONTACTS: 'NONE',
      MANAGE_VERIFICATION_BODIES: 'NONE',
      ADD_OPERATOR_ADMIN: 'NONE',
      ASSIGN_REASSIGN_TASKS: 'EXECUTE',
      REVIEW_PERMIT_APPLICATION: 'VIEW_ONLY',
      PEER_REVIEW_PERMIT_APPLICATION: 'VIEW_ONLY',
      REVIEW_PERMIT_SURRENDER: 'VIEW_ONLY',
      PEER_REVIEW_PERMIT_SURRENDER: 'VIEW_ONLY',
      SUBMIT_PERMIT_REVOCATION: 'VIEW_ONLY',
      PEER_REVIEW_PERMIT_REVOCATION: 'VIEW_ONLY',
      REVIEW_PERMIT_NOTIFICATION: 'VIEW_ONLY',
      PEER_REVIEW_PERMIT_NOTIFICATION: 'VIEW_ONLY',
      SUBMIT_REVIEW_PERMIT_VARIATION: 'VIEW_ONLY',
      PEER_REVIEW_PERMIT_VARIATION: 'VIEW_ONLY',
      REVIEW_AER: 'VIEW_ONLY',
    },
  },
  {
    name: 'Regulator team leader',
    code: 'regulator_team_leader',
    rolePermissions: {
      REVIEW_INSTALLATION_ACCOUNT: 'EXECUTE',
      MANAGE_USERS_AND_CONTACTS: 'NONE',
      MANAGE_VERIFICATION_BODIES: 'NONE',
      ADD_OPERATOR_ADMIN: 'NONE',
      ASSIGN_REASSIGN_TASKS: 'EXECUTE',
      REVIEW_PERMIT_APPLICATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_APPLICATION: 'EXECUTE',
      REVIEW_PERMIT_SURRENDER: 'EXECUTE',
      PEER_REVIEW_PERMIT_SURRENDER: 'EXECUTE',
      SUBMIT_PERMIT_REVOCATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_REVOCATION: 'EXECUTE',
      REVIEW_PERMIT_NOTIFICATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_NOTIFICATION: 'EXECUTE',
      SUBMIT_REVIEW_PERMIT_VARIATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_VARIATION: 'EXECUTE',
      REVIEW_AER: 'EXECUTE',
    },
  },
  {
    name: 'CA super user',
    code: 'ca_super_user',
    rolePermissions: {
      REVIEW_INSTALLATION_ACCOUNT: 'EXECUTE',
      MANAGE_USERS_AND_CONTACTS: 'EXECUTE',
      MANAGE_VERIFICATION_BODIES: 'EXECUTE',
      ADD_OPERATOR_ADMIN: 'EXECUTE',
      ASSIGN_REASSIGN_TASKS: 'EXECUTE',
      REVIEW_PERMIT_APPLICATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_APPLICATION: 'EXECUTE',
      REVIEW_PERMIT_SURRENDER: 'EXECUTE',
      PEER_REVIEW_PERMIT_SURRENDER: 'EXECUTE',
      SUBMIT_PERMIT_REVOCATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_REVOCATION: 'EXECUTE',
      REVIEW_PERMIT_NOTIFICATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_NOTIFICATION: 'EXECUTE',
      SUBMIT_REVIEW_PERMIT_VARIATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_VARIATION: 'EXECUTE',
      REVIEW_AER: 'EXECUTE',
    },
  },
  {
    name: 'PMRV super user',
    code: 'pmrv_super_user',
    rolePermissions: {
      REVIEW_INSTALLATION_ACCOUNT: 'EXECUTE',
      MANAGE_USERS_AND_CONTACTS: 'EXECUTE',
      MANAGE_VERIFICATION_BODIES: 'EXECUTE',
      ADD_OPERATOR_ADMIN: 'EXECUTE',
      ASSIGN_REASSIGN_TASKS: 'EXECUTE',
      REVIEW_PERMIT_APPLICATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_APPLICATION: 'EXECUTE',
      REVIEW_PERMIT_SURRENDER: 'EXECUTE',
      PEER_REVIEW_PERMIT_SURRENDER: 'EXECUTE',
      SUBMIT_PERMIT_REVOCATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_REVOCATION: 'EXECUTE',
      REVIEW_PERMIT_NOTIFICATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_NOTIFICATION: 'EXECUTE',
      SUBMIT_REVIEW_PERMIT_VARIATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_VARIATION: 'EXECUTE',
      REVIEW_AER: 'EXECUTE',
    },
  },
  {
    name: 'Regulator technical officer',
    code: 'regulator_technical_officer',
    rolePermissions: {
      REVIEW_INSTALLATION_ACCOUNT: 'EXECUTE',
      MANAGE_USERS_AND_CONTACTS: 'NONE',
      MANAGE_VERIFICATION_BODIES: 'NONE',
      ADD_OPERATOR_ADMIN: 'NONE',
      ASSIGN_REASSIGN_TASKS: 'EXECUTE',
      REVIEW_PERMIT_APPLICATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_APPLICATION: 'EXECUTE',
      REVIEW_PERMIT_SURRENDER: 'EXECUTE',
      PEER_REVIEW_PERMIT_SURRENDER: 'EXECUTE',
      SUBMIT_PERMIT_REVOCATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_REVOCATION: 'EXECUTE',
      REVIEW_PERMIT_NOTIFICATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_NOTIFICATION: 'EXECUTE',
      SUBMIT_REVIEW_PERMIT_VARIATION: 'EXECUTE',
      PEER_REVIEW_PERMIT_VARIATION: 'EXECUTE',
      REVIEW_AER: 'EXECUTE',
    },
  },
];

export const mockRegulatorPermissionGroups = {
  REVIEW_INSTALLATION_ACCOUNT: ['NONE', 'VIEW_ONLY', 'EXECUTE'],
  MANAGE_USERS_AND_CONTACTS: ['NONE', 'EXECUTE'],
  MANAGE_VERIFICATION_BODIES: ['NONE', 'EXECUTE'],
  ADD_OPERATOR_ADMIN: ['NONE', 'EXECUTE'],
  ASSIGN_REASSIGN_TASKS: ['NONE', 'EXECUTE'],
  REVIEW_PERMIT_APPLICATION: ['NONE', 'VIEW_ONLY', 'EXECUTE'],
  PEER_REVIEW_PERMIT_APPLICATION: ['NONE', 'VIEW_ONLY', 'EXECUTE'],
  REVIEW_PERMIT_SURRENDER: ['NONE', 'VIEW_ONLY', 'EXECUTE'],
  PEER_REVIEW_PERMIT_SURRENDER: ['NONE', 'VIEW_ONLY', 'EXECUTE'],
  SUBMIT_PERMIT_REVOCATION: ['NONE', 'VIEW_ONLY', 'EXECUTE'],
  PEER_REVIEW_PERMIT_REVOCATION: ['NONE', 'VIEW_ONLY', 'EXECUTE'],
  REVIEW_PERMIT_NOTIFICATION: ['NONE', 'VIEW_ONLY', 'EXECUTE'],
  PEER_REVIEW_PERMIT_NOTIFICATION: ['NONE', 'VIEW_ONLY', 'EXECUTE'],
  SUBMIT_REVIEW_PERMIT_VARIATION: ['NONE', 'VIEW_ONLY', 'EXECUTE'],
  PEER_REVIEW_PERMIT_VARIATION: ['NONE', 'VIEW_ONLY', 'EXECUTE'],
  REVIEW_AER: ['NONE', 'VIEW_ONLY', 'EXECUTE'],
};
